### ISSUE TITLE
Level of Assurances need to be defined

### ISSUE THREAD

**Issue by RalphBragg** [OpenBanking-Brasil/specs-seguranca#1]
The current drafts do not include any definitions of what loa2 or loa3 authentication requirements are. The GT Security and GT Security and Fraud need to define them and propose a pull request for the appropriate text.

**Comment by DeiGratia33** [comment]
Decision (Executive approval in progress)

LoA2: Single factor 
LoA3: Multifactor


With the following conditionals:
read-only: At least LoA2. The ASPSP could for your own decision raise the authentication to LoA3.
read-write: At least LoA3.

**Comment by RalphBragg** [comment]
Just to confirm that when you define 'different factor' you mean a different knowledge factor. e.g, 2 knowledge factors is not sufficient? Are there going to be any additional definitions of what a 'secure' knowledge factor is? 

Authentication Factor Categories
Authentication factors are traditionally split into these three categories: knowledge, possession, and inherence. Each of these categories gets a separate article in the PSD2 RTS:

Knowledge refers to typically a PIN or a password. In article 6 the payment service providers are required to mitigate disclosure of the knowledge factor.
Possession can be either a token used for authentication, but it can also be the possession of a device if it has earlier been proven that the device belongs to a user. In article 7 the payment service providers are required to mitigate replication of the possession factor.
Inherence is basically “metrics intrinsically owned by an individual”. This is typically fingerprint, face recognition or voice recognition. In article 8 the payment service providers are required to protect access to the inherence factor.

**Comment by DeiGratia33** [comment]
The FAQ page has included the necessary information about authentication methods.

**Comment by RalphBragg** [comment]
This was closed with the last PR.
