### ISSUE TITLE
Question: Unstructured access tokens, JWT ATs or both?

### ISSUE THREAD

**Issue by alexasensio** [OpenBanking-Brasil/specs-seguranca#103]
On defining the format of the access tokens, my understanding is that OBB FAPI 1 ID1 does not specify anything and therefore does not modify FAPI 1.0 Final. The Notes from [FAPI 1.0 Final Part 1: Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0-final.html#authorization-request-and-response) mentions that "Authorization servers can issue unstructured or structured access tokens (for example, a signed JWT)." So my understanding is that both options are allowed.

However, some in-revision documentation from Febraban says that AT will be JWTs, and Github prior to 2021.06.09 used to contain mentions to JWT access tokens (see [rc6.5](https://openbanking-brasil.github.io/areadesenvolvedor/versions/v1.0.0-rc6.5/#em-revisao-fluxos-de-autenticacao-e-autorizacao)): 

"Diagrama – Fluxo de credenciais do client.

1. O client e o servidor de autenticação estabelecem uma conexão mTLS, e o Client solicita um Access Token.
2. O Servidor de Autenticação gera uma impressão digital SHA-256 do certificado do Client e a incorpora em um **Access Token JWT**. Isto limita o Access Token ao Client."

Can banks choose unstructured access tokens also?

**Comment by RalphBragg** [comment]
Hi,

The Audience from a Banks issued Access token is a Banks Resource Server. So the Access token can be anything that a Bank can issue that a Bank can read... so it can be whatever format a bank wants too.

An access token contents should really only be accessible to the intended audience. So a reference token that is introspected by a resource server or a encrypted JWE (which looks to a TPP just like a reference token) is also a way to go. 
Unencrypted JWTs are actually a sub optimal solution as Banks AS's may need to put into an AT all sorts of stuff about the subject, that might inform access decisions and that information is unnecessary or could have LGDP implications if accessible to a TPP.

So yes, Banks can issue access tokens in whatever format they like. I would personally like this tightened to make sure that Banks, if using JWTs, DO NOT put anything that could be sensitive in an access token if the contents is accessible to a TPP and to be clear, a JWT's contents IS accessible to a TPP.

**Comment by RalphBragg** [comment]
Answer: **Banks** can use whatever structure of Access Tokens they like provided the **Banks Own Resource Servers** can read them (which should be obvious). Banks that choose to use unencrypted structured access tokens must ensure that the contents of the access tokens do not reveal any resource owner personal data or other data that the TPP is not authorised to receive.

**Comment by RalphBragg** [comment]
Improvement Ticket #104  raised to make this more clear and to highlight the potential privacy concerns if structured tokens are used incorrectly.

**Comment by alexasensio** [comment]
Thanks for clarifying. Answer is what I expected.

For clarity, in all points above I was implying JWEs, and not JWTs only, as [FAPI Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0-final.html#authorization-request-and-response) requires that: "The Authorisation Server 16. shall provide non-guessable access tokens,[...]"

**Comment by RalphBragg** [comment]
The issue with JWT's that they're still non guessable. You can't just make them up but they aren't privacy preserving.
JWEs are non guessable and privacy preserving.
