### ISSUE TITLE
ID2: Guidance and Clarification on the use of 'Structured Access Tokens'

### ISSUE THREAD

**Issue by RalphBragg** [OpenBanking-Brasil/specs-seguranca#104]
There is mixed messages regarding the use of structured access tokens both within the brazil security profile and FAPI. Whilst structured access tokens are permitted, unstructured, by reference tokens are also permitted which is perfectly acceptable. 

The intended audience of an Access Token issue by a Bank is the Banks own Resource Server. Provided the Resource Server has a way of accessing the information about the token either by using introspection or by processing the structured token then nothing further needs to be defined.

Where care and potential clarification is required is to make it explicit that that Relying Party (TPP) is not the intended audience of an access token and thus has no need to know the contents of the AT. In addition, Banks that rely on structured access tokens need to be make sure that they either encrypt the contents of the token so that only the RS can process the contents of the token OR that they are 100% certain that the contents of their ATs are not leaking confidential or sensitive information, potentially covered by LGDP, to the TPP.

This is important enough that it warrants an additional clause in the security profile .

**Comment by bernardoVale** [comment]
Adding my two cents here @RalphBragg. It also might be a good idea to mention that if you're using structured access tokens you cannot only rely on signature verification in your resource server because tokens might get revoked by the TPP.

**Comment by michellebandarraChicago** [comment]
Hi guys, this issue is still valid or should we close it?

**Comment by michellebandarraChicago** [comment]
Security WG concluded that the existing regulation already provides information about Access token encryption, as well as the mandatory encryption of the channel with the confidential client. Hence, the decision regarding the data to be included in the access token, as well as its encryption or not, is up to each institution according to its cybersecurity policies and risk profile.
