### ISSUE TITLE
Typo: OBB DCR

### ISSUE THREAD

**Issue by TakahikoKawasaki** [OpenBanking-Brasil/specs-seguranca#107]
**Section 5, the last paragraph**
"Langauges" -> "Languages"

**Section 6.1, Clause 6**
"Pushed Authorisation Requests" -> "Pushed Authorization Requests"

**Section 7.1, Clause 12**
"authenication" -> "authentication"

**Section 7.1.2, the last paragraph**
"descripters" -> "descriptors"

**Section 7.2.1**
"fine grained" -> "fine-grained"

**At many places**
Orthographical variants between "authorisation" (British English) and "authorization" (American English).

**Comment by RalphBragg** [comment]
Feel free to raise a PR directly, I'm sure someone will get onto these at some point. Thanks for the detailed review.
