### ISSUE TITLE
Typo: OBB FAPI

### ISSUE THREAD

**Issue by TakahikoKawasaki** [OpenBanking-Brasil/specs-seguranca#108]
**Introduction, the first paragraph**
"Area area" -> "area"

**Section 5.1, the 2nd bullet**
"fine grained" -> "fine-grained"

**Section 5.2.2.2, the 2nd paragraph**
"an cpf Claim" -> "a cpf Claim"

**Section 5.2.2.3, the 3rd paragraph**
"an cnpj Claim" -> "a cnpj Claim"

**Section 5.2.3, Clause 2**
"pushed authorisation requests" -> "pushed authorization requests"

**Section 7.2.1**
"REST Resouces" -> "REST Resources"

**Section 7.2.2, Clause 6**
"acoordance" -> "accordance"

**Comment by RalphBragg** [comment]
Ta - corrected.
