### ISSUE TITLE
Docs for well-known resource config

### ISSUE THREAD

**Issue by samlarsen1** [OpenBanking-Brasil/specs-seguranca#110]
The current docs for the well-known resource config are unclear:
https://openbanking-brasil.github.io/specs-seguranca/aspsp-user-guide.html#13-registering-resources

Do we create a well-known endpoint for each set of versioned APIs?  Are there any real examples of these files you can point us to?

Or are these the same well-known files that define our authorization server config?

**Comment by RalphBragg** [comment]
The well-knowns are not required for each versioned APIs. Several Banks have configured their authorization server metadata and their functional API endpoints on the directory already. I'll find a good reference and include it here.

**Comment by michellebandarraChicago** [comment]
Hi guys, is this issue still valid or should we close it?

**Comment by joaorodolfo** [comment]
@RalphBragg did you have some reference to include here? if not, we can close this ticket. Thanks.

**Comment by pedro-octavio-andrade** [comment]
@samlarsen1 @RalphBragg  is this issue still valid? The issue is already solved by the documentations?

**Comment by michellebandarraChicago** [comment]
Tema enviado para tratativa pelo GT Especificações
