### ISSUE TITLE
Question: Client Authentication Method at Introspection and Revocation Endpoints

### ISSUE THREAD

**Issue by TakahikoKawasaki** [OpenBanking-Brasil/specs-seguranca#111]
The example in "[9.1. Posting a request with a software statement](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html#name-posting-a-request-with-a-so)" in "[Open Banking Brasil Financial-grade API Dynamic Client Registration 1.0 Implementers Draft 1](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html)" contains `introspection_endpoint_auth_method` and `revocation_endpoint_auth_method` like below.

```
"introspection_endpoint_auth_method": "private_key_jwt",
"revocation_endpoint_auth_method": "private_key_jwt",
```

[RFC 8414](https://www.rfc-editor.org/rfc/rfc8414.html) defines `introspection_endpoint_auth_methods_supported` and `revocation_endpoint_auth_methods_supported` server metadata, but there are no corresponding client metadata like `introspection_endpoint_auth_method` and `revocation_endpoint_auth_method` in [OpenID Connect Dynamic Client Registration 1.0](https://openid.net/specs/openid-connect-registration-1_0.html) and [RFC 7591](https://www.rfc-editor.org/rfc/rfc7591.html). Does Open Banking Brasil define these client metadata somewhere?

RFC 8414 defines server metadata that list supported client authentication methods per endpoint. However, the practice is now regarded as bad. It is why `backchannel_authentication_endpoint_auth_methods_supported` server metadata was not defined in [CIBA Core](https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html). See the discussion in [[MODRNA Issue 103] CIBA: Metadata for client auth at backchannel endpoint](https://bitbucket.org/openid/mobile/issues/102) for details.

**Comment by RalphBragg** [comment]
Open Banking does not define these explicitly and there is no requirement to support or include them on the response however it is not a failing scenario if they are included on the response either as they are defined in the RFCs that you mentioned. The endpoint authentication mechanisms must be FAPI compliant. I'll remove these endpoint values from the responses for the sake of clarity.

**Comment by joaorodolfo** [comment]
@RalphBragg should we close it or we have to include some clause into FAPI Brazil Doc? Thanks
