### ISSUE TITLE
Question: Where do i find instructions on how to query the directories APIs?

### ISSUE THREAD

**Issue by samlarsen1** [OpenBanking-Brasil/specs-seguranca#119]
Is the directory API for Phase 2 different to Phase 1?  We expect it is because the phase 1 API is open and not token secured, also the swagger for phase 2 is different in structure and uri.  We would also like to confirm that the directory data is different.

Please confirm.

Thank you

**Comment by RalphBragg** [comment]
Hi - The directory swagger has been published on the main repository) and the usage instructions for obtaining and using an access tokens are included on the aspsp and tpp user guides.

**Comment by ediemerson-br** [comment]
If you have further question, you can create a service desk ticket.
https://servicedesk.openbankingbrasil.org.br/Login.jsp
