### ISSUE TITLE
ICP Brasil CNPJ Field

### ISSUE THREAD

**Issue by EkkeErick** [OpenBanking-Brasil/specs-seguranca#12]
We need the Security WG to clarify about the format of the CNPJ. 
On the ICP Profile it says it's a number of 14 digits. 

Considering the issues we may find with the leading zeroes on the CNPJ we need to understand if it must be stored as a string, or as a number of up to 14 digits, zero padded. After this definition we will set it accordingly on the json libraries.

**Comment by RalphBragg** [comment]
I have no preference either way however it would be good to get security and the api teams to provide an opinion. It is documented in different ways in different specifications so it would be good to pick a standard and align to it if possible.

**Comment by EkkeErick** [comment]
Answer on Behalf of Security WG: Short Answer: You can consider it as a string.
                
But thinking about filling in the field with 14 positions and filling in with “0” in the absence of data and, in addition, in cases where CPNJ starts with “0” too, I understand that the field should be in the string format.

Even the CNPJ OID in the e-CNPJ is a string.

According to the RFC on the subject "The set of information defined in each otherName field must be stored as a string of type ASN.1 OCTET STRING or PRINTABLE STRING" (https://tools.ietf.org/html/rfc5280. html)
