### ISSUE TITLE
Question: refresh token expiration date after refreshing

### ISSUE THREAD

**Issue by TakahikoKawasaki** [OpenBanking-Brasil/specs-seguranca#123]
The 1st clause in "[7.2.2. Authorization server](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-financial-api-1_ID1.html#name-authorization-server-2)" of "[Open Banking Brasil Financial-grade API Security Profile 1.0 Implementers Draft 1](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-financial-api-1_ID1.html)" states as follows.

> shall issue refresh tokens with validity equal to the _expirationDateTime_ defined on the linked Consent Resource;

So, the first refresh token will expire at the time indicated by the _expirationDateTime_.

What should happen when a refresh token request (= a token request with `grant_type=refresh_token`) is made?

1. Should a new refresh token be issued?
2. If a new refresh token is issued, should the new one take over the expiration date of the previous one or should it have a new different expiration date?

**Comment by DeiGratia33** [comment]
We have an open issue  #75 to clarify the intent of this item.

**Comment by RalphBragg** [comment]
@TakahikoKawasaki  - the intent is simple, when the consent expires (and they can't be extended currently) then the 'grant' is expired. Refresh, ATs etc should no longer permit access to the resource.

**Comment by TakahikoKawasaki** [comment]
@RalphBragg Thank you. If so, options for authorization server implementations will be either

1. not issue a new refresh token and not revoke the used refresh token after use, or
2. issue a new refresh token but the new one takes over the remaining lifetime of the used one.

The first option will be easier for most authorization server implementations.

**Comment by RalphBragg** [comment]
Hi @TakahikoKawasaki  - are you talking about refresh token rotation? i.e issue a new refresh token after every use? I thought that this was clarified by the FAPI WG? (i.e don't) Australia tried it and it was an unmitigated disaster. 

Option 1 for my money. I'll check that this isn't defined any where and then propose an enhancement to make it explicit, please don't use refresh token rotation.

**Comment by TakahikoKawasaki** [comment]
The second option is "refresh token rotation". I don't remember whether it was clarified in FAPI WG calls. I mean I was not listening to discussion related to it carefully.

What I noticed now is that expiration date of access tokens issued by refresh token requests (= token requests with `grant_type=refresh_token`) must not exceed the `expirationDateTime` of the consent, if the rationale behind `expirationDateTime` is so. Probably, authorization server implementations will have to customize their behaviors for the requirement. It may be better to write it explicitly somewhere in the specification.

**Comment by RalphBragg** [comment]
I agree - https://github.com/OpenBanking-Brasil/specs-seguranca/issues/129 Australias experimentation with this should be a lesson learned. It's still a problem that remains unresolved.

**Comment by TakahikoKawasaki** [comment]
It seems that the content of the 1st clause in "7.2.2. Authorization Server" has been changed from

>shall issue refresh tokens with validity equal to the expirationDateTime defined on the linked Consent Resource;

to

>shall only issue refresh tokens when linked to active and valid consent;

According to the new clause, it is technically allowed to issue a refresh token whose lifetime is longer than the lifetime of the corresponding consent. At least, it is difficult, if not impossible, for readers to think that the lifetime of the refresh token should not exceed the lifetime of the consent.

If the authorization server is notified of expiry of the consent without delay and revokes the refresh token promptly on the notification, the lifetime of the refresh token won't be an issue even if it is longer than that of the consent. However, otherwise, the refresh token can live longer than the consent.

**Comment by RalphBragg** [comment]
This wording is wrong. I'll check who raised and approved the pull request.

**Comment by joaorodolfo** [comment]
It's handled into:
https://github.com/OpenBanking-Brasil/specs-seguranca/issues/75
https://github.com/OpenBanking-Brasil/specs-seguranca/pull/145
https://github.com/OpenBanking-Brasil/specs-seguranca/pull/215
