### ISSUE TITLE
Question: How to bound selected account with consent?

### ISSUE THREAD

**Issue by Wesley-Alves** [OpenBanking-Brasil/specs-seguranca#125]
According to the user guide document (https://openbanking-brasil.github.io/areadesenvolvedor/documents/GuiaDeExperienciaDoUsuarioCompartilhamentoDeDadosEIniciacaoDePagamento.pdf, page 90), in the data sharing consent authorization process, the user can select a source account of their data to associate with the consent

So is there any standardized way to associate user-selected data, in this case the account ID, with consent? Would this part of associating data to consent be a bank-specific implementation?

**Comment by RalphBragg** [comment]
This is bank specific though consult the 'Resources API' to see how you'll need to track authorisations and potentially multiple party authorisations.

**Comment by ediemerson-br** [comment]
If you have further question, you can create a service desk ticket.
https://servicedesk.openbankingbrasil.org.br/Login.jsp
