### ISSUE TITLE
Question: How to enforce encrypted request object during DCR

### ISSUE THREAD

**Issue by ju-cu** [OpenBanking-Brasil/specs-seguranca#127]
The [OBB FAPI 1 DCR Profile](https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-dynamic-client-registration-1_ID1.md#authorization-server-1) has the following requirement on Authorization Servers:

> 8. shall require encrypted request objects as required by the Brasil Open Banking Security Profile

To my understanding encrypted request objects are required by the Brasil Open Banking Security Profile and part of the authorization, i.e. when requesting a token. However, I do not understand how this requirement fits into the DCR flow.

Can anyone explain how to fulfill this requirement, i.e. which metadata field that the AS must verify during client registration?

**Comment by RalphBragg** [comment]
This clause in DCR is missing a 'shall require support for'. The obligation as defined on the security profile is for Banks to support encrypted request objects if not enforcing the use of PAR.

The obligation is on the **RP** to use encrypted request objects and for the banks to support their use or use PAR.

A clarification perhaps should be to check for the presence of request_object_encryption_alg and request_object_encryption_enc values on the request however it is also perfectly valid for a Bank to default these on the response.

**Comment by ju-cu** [comment]
That was my understanding as well. 

Even if the client includes `request_object_encryption_enc` and `request_object_encryption_alg`, it is not obliged to encrypt the request object as the parameters only list the client's preferred algorithm. From [OIDR](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata)

> The RP MAY still use other supported encryption algorithms or send unencrypted Request Objects, even when this parameter is present.

I'll wait for an updated version of the draft. Thank you for your answer.
