### ISSUE TITLE
Question: How to get "regulatory role" from SSA?

### ISSUE THREAD

**Issue by ju-cu** [OpenBanking-Brasil/specs-seguranca#128]
[OBB FAPI 1 DCR] specifies the following requirement for Authorization Servers:

> 9. shall validate that requested scopes are appropriate for the softwares authorized regulatory roles;

The [example software statement](https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-dynamic-client-registration-1_ID1.md#software-statement-claims) contains multiple claims for roles: `software_statement_roles` and `software_roles`. As there is no description of the claims (reported in #84) it is not obvious to me why this data is included twice. Please clarify which field (or fields) of the software statement that the Authorization Server should read the "regulatory role" from.

**Comment by RalphBragg** [comment]
https://github.com/OpenBanking-Brasil/specs-seguranca/issues/85
Please refer to previous question

**Comment by ju-cu** [comment]
Ah, sorry. Missed to browse through the closed questions. Thanks!
