### ISSUE TITLE
Remove unintentional support for refresh token rotation.

### ISSUE THREAD

**Issue by RalphBragg** [OpenBanking-Brasil/specs-seguranca#129]
A question was raised covering the behaviour of refresh tokens and whether a new refresh token should be issued when one is presented. ala, refresh token rotation. The support for refresh token rotation poses significant challenges for the ecosystem especially if a refresh token is lost. Whilst it is possible to 're-consent' an existing consent, this would require customer interaction which is undesirable. There is no standard way to cater for this event.

Australia has experimented with refresh token rotation and some of the outcomes were less than ideal.  https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/219 and the support for refresh token rotation is still causing challenges today. 

As the refresh token is a credential that is bound to the client, requires authentication, requires presentation down a mutually authenticated tls channel and the client authentication mechanisms used by Brazil are sufficiently secure. The rotation of this fresh token credential, when compared against the perceived risk vs reward, introduces unnecessary complexity for participants and potentially significant impact to customers.

**Comment by michellebandarraChicago** [comment]
Hi Ralph. My understanding is that #215 solved this issue. Is that right?

**Comment by joaorodolfo** [comment]
It's handled into:
https://github.com/OpenBanking-Brasil/specs-seguranca/pull/215
