### ISSUE TITLE
ClientID  on Plan Test Guide 

### ISSUE THREAD

**Issue by FrancoPeluti** [OpenBanking-Brasil/specs-seguranca#131]
Hello there,

     At this guide https://openbanking-brasil.github.io/areadesenvolvedor/documents/Guia_OBB.pdf, page 18  item 11 of Requirements, says that "Add the client_id from the SSA issued by the Directory"  but I think It should be the one issued by the ASPSP DCR. Is this understanding correct?

**Comment by RalphBragg** [comment]
Your understanding is correct; this guide is incorrect.

**Comment by FrancoPeluti** [comment]
thx Ralph
