### ISSUE TITLE
Missing "Resources" API scope from Default Scope list for DADOS.

### ISSUE THREAD

**Issue by alexasensio** [OpenBanking-Brasil/specs-seguranca#134]
- Is there a scope for accessing the /resources API?

https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html#section-7.2 Does not have any "resources" scope at the moment, however: the /resource API swagger requires permission "RESOURCES_READ" and according to the (deleted, see issue [OpenBanking-Brasil/areadesenvolvedor/#176](https://github.com/OpenBanking-Brasil/areadesenvolvedor/issues/176)) mapping of roles-scopes-permissions, this permission is linked to scope resources. 
<img width="1418" alt="Screenshot 2021-06-23 at 12 15 05" src="https://user-images.githubusercontent.com/9254804/123087605-a659ae00-d41c-11eb-894b-f1dc0027652a.png">

If that spreadsheet is valid, then I think we need a scope "resources" associated to the "DADOS" role in the DCR spec Section 7.2.
If that spreadsheet is not valid anymore, then what is the scope associated to "RESOURCES_READ" permission? _openid_?

**Comment by RalphBragg** [comment]
The spreadsheet is correct, at least for this issue. In addition the scope is defined on the actual API resource itself (which is master). https://openbanking-brasil.github.io/areadesenvolvedor/swagger/swagger_resources_apis.yaml

@ginglass is in fine form this morning with addressing these so this should be a quick fix. Good spot.

**Comment by RalphBragg** [comment]
@ginglass: Can you do the honours please and add yet another scope to the allowable / default scopes for a DADOS. It would be great if for ID2 this could be looked at holistically. Why do you have a permission for resources and a 'scope' when you only have one permission.

Needing both a scope and permission when actually both a synonymous at the moment for each other is just another area where TPPs can stuff themselves up unnecessarily. 

One for a later draft - in the meantime just adding this scope to the default scope list will have to suffice.

**Comment by ginglass** [comment]
Hi @RalphBragg . I raised this issue yesterday at Sec WG. We address this issue to Spects WG to help fix it.  Don´t make any sense define a permission to this API if any consent is made. I think that "consents" scope (and an dynamic consent related) wold be sufficient, don´t you agree?. So there is no issue to DCR or security profile... just adjusts at swagger file. Do you agree @GislaineAlmeida  and @alex-siqueira ?

**Comment by RalphBragg** [comment]
Honestly - i'd suggest removing scopes entirely from all of the other APIs. Every AS is going to have to evaluate permissions for 90% of the APIs. Why would you want to have this one as 'special'. I would have thought that implementers would have preferred a consistent pattern both for consent and also resource security rather than a mixed mode.

**Comment by ginglass** [comment]
Permissions will be shown to customer and if the customer doesn´t consent with this one (resource_read) there is no consent at all... this one should not be presented as an option to users. Permissions could be implemented outside AS (RP can implement this verification), so I don´t know if 90% of permissions controls will be made by the AS itself.

**Comment by RalphBragg** [comment]
Correct - the customer has consented to the permission. So from a security point of view i need to know the permission... the scope offers nothing. So drop the scope.

**Comment by ginglass** [comment]
Permissions have to be shown at consent page, right? So do you believe that customers must have the option to choose to give or not this specific permission? I don´t think it´s a goog idea.

I agree that could be sufficient a basic scope (I thouht "consents" but can be a specific one "resources" - for now - or no scope at all - let me check with specs/security guys, right?). The RP of "resources API" (or AS/API gw) have to grant access just to data related to consetId  linked to access_token, so if a TTP has a token it means that it has a consent.
