### ISSUE TITLE
Missing section in "Third Party Provider End To End User Guide"

### ISSUE THREAD

**Issue by menecio** [OpenBanking-Brasil/specs-seguranca#137]
Here at [4.3.5 Access Resources](https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/tpp-user-guide.md#435-access-resources) it mentions 

> With the access token that was returned in 4.2.3, the TPP now has the ability to call customers resources.

But there is no 4.2.3 section under 4.2

**Comment by ginglass** [comment]
You´re correct. It means 4.3.3 as in portuguese version. Will fix it on next PR.

https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/tpp-user-guide-ptbr.md#435-acesso-aos-recursos--acessorecursos
