### ISSUE TITLE
Question: How do refresh tokens work?

### ISSUE THREAD

**Issue by menecio** [OpenBanking-Brasil/specs-seguranca#138]
It's not clear how refresh token support will work, [here](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-financial-api-1_ID1.html#name-authorization-server) in the "Open Banking Brasil Financial-grade API Security Profile 1.0 Implementers Draft 1" in section 5.2.2.12  it's stated that:

> shall support refresh tokens

But then in the [TPP End-to-End Guide](https://openbanking-brasil.github.io/specs-seguranca/tpp-user-guide.html), I can't find any mentions about refresh tokens anywhere.

More specific, my question is about this flow in particular
![image](https://user-images.githubusercontent.com/924245/123140272-6237cf00-d457-11eb-94d7-d431d25bab92.png)

In the Authorization Token Exchange response:
1. will there be a refresh token too?
2. if so, how can a TPP use the refresh token to renew the access token?

**Comment by RalphBragg** [comment]
Support for refresh tokens and how they’re used is defined in the base oauth 2 specification. Rfc6749

**Comment by RalphBragg** [comment]
Closing - marked as answered with no followup questions.
