### ISSUE TITLE
Auth flow detailment

### ISSUE THREAD

**Issue by andreborges01** [OpenBanking-Brasil/specs-seguranca#14]
Both guides must show in more detail every single step that is necessary to follow and understand whole flow related with authorization and authentication process, including details about how TTP client and the Authorizarion Server gets all necessary public keys (and certificates - including which kind of certificates - and "key usage" - are necessary) and every step to TTP encrypt ans ASPSP (especially the Authorization Server) decrypt JWE. Does "key  encipherment" key usage is sufficient do make it work?

**Comment by RalphBragg** [comment]
Both of these are drafts with a lot more explicit examples to come. once the security profiles have been signed off.

**Comment by RalphBragg** [comment]
@andreborges01 - Can we have discussion on this and what you think TPPs might need? I was planning on uploading a complete end2end application that contains all of the steps so that a TPP could explore for themselves and see all of the interactions that are made.

**Comment by ediemerson-br** [comment]
@andreborges01 - have you checked the latest guides versions? Did they address your needs?

**Comment by ediemerson-br** [comment]
If you have further questions, you can create a service desk ticket.
https://servicedesk.openbankingbrasil.org.br/Login.jsp
