### ISSUE TITLE
Questions: Userinfo access token

### ISSUE THREAD

**Issue by alexasensio** [OpenBanking-Brasil/specs-seguranca#140]
The userinfo endpoint requires an access token according to OIDC Section 5.3 https://openid.net/specs/openid-connect-core-1_0.html#UserInfo

1. What is the required scope of this token? openid?

2. I am assuming that the identification of which customer's userinfo details are requested by the TPP is only known because the access token is linked to a given consentId. Is that correct?

**Comment by RalphBragg** [comment]
1. openid - This is a core part of openid connect, the userinfo endpoint is accessible using an access token that has scope openid so technically ALL access tokens (except the consents creation access token) could be used to access the user info endpoint.

"The UserInfo Endpoint is an OAuth 2.0 Protected Resource that returns Claims about the authenticated End-User. To obtain the requested Claims about the End-User, the Client makes a request to the UserInfo Endpoint using an Access Token obtained through OpenID Connect Authentication."

All user authentication flows are performed using OpenID Connect which is implied or activated by using the scope 'openid'

2. No, the access token was issued with a scope of 'openid', how the Bank then links the Access Token to the user subject is up to each implementation however typically you will see implementors add a claim of 'sub' or 'subject' defined in an AT

**Comment by RalphBragg** [comment]
Closing - marked as answered with no followup questions.
