### ISSUE TITLE
GET/accounts Credit card accounts permissions - clarification question

### ISSUE THREAD

**Issue by mariatagalaki** [OpenBanking-Brasil/specs-seguranca#146]
hi all, 

I have a question regarding the mapeamento_roles_permissions published [here ](https://github.com/OpenBanking-Brasil/areadesenvolvedor/blob/196bf4779a6a7ce5b651193e68fa77c09e217619/documents/Mapeamento_roles_permissions.xlsx)

- I understand that for the **CREDIT_CARDS_ACCOUNTS_BILLS_READ** permission the **CREDIT_CARDS_ACCOUNTS_READ** permission should be requested. 
- I understand that when both **CREDIT_CARDS_ACCOUNTS_BILLS_READ** and **CREDIT_CARDS_ACCOUNTS_TRANSACTIONS_READ** are requested together, both **CREDIT_CARDS_ACCOUNTS_READ
CREDIT_CARDS_ACCOUNTS_BILLS_TRANSACTIONS_READ** permissions should be requested; _is this correct?_ 
- Are there any specific permissions required for the _CREDIT_CARDS_ACCOUNTS_BILLS_TRANSACTIONS_READ?_ 
- In case the TPP doesn't request the adequate group of permissions, the error response is a 400, right?

could you please clarify? Thanks!

**Comment by alexasensio** [comment]
@ginglass @alex-siqueira @RalphBragg @mariatagalaki   this can be closed

**Comment by RalphBragg** [comment]
The correct behaviour has been implemented in the conformance and certification tests.
