### ISSUE TITLE
Poll: Does publication of Banks Authorization Server locations and available API Services and Endpoints publicly pose a security risk? [Please Vote - Tick up or Down]

### ISSUE THREAD

**Issue by EkkeErick** [OpenBanking-Brasil/specs-seguranca#147]
For the data extract of the directory the security WG said that Raidiam  can display both Phase 1 And Phase 2 APIs. 

No need to filter it out.

If you understand that this might pose a security issue please reply. Otherwise let's go with them.

**Comment by joaorodolfo** [comment]
It's no longer more necessary.
