### ISSUE TITLE
Open Banking Brasil Certificates Usage Clarifications

### ISSUE THREAD

**Issue by leandrobarra** [OpenBanking-Brasil/specs-seguranca#149]
The Open Banking Brasil ecosystem uses 4 types of certificates.

Server Certificate (5.2.1) - API endpoints
Client Certificate (5.2.2) - authenticate mTLS/authenticate client
Signature Certificate (5.2.3) - to sign the JWT
Front-End Certificates (5.2.4) - for front-end access

Discussing in a security gt, some doubts were not clarified:

Server Certificate (5.2.1) - Can Wildcard SSL be used?

Client Certificate (5.2.2) - do participants, who will join open banking on August 30th, without clients, need a client certificate?

Front-End Certificates (5.2.4) - Does the developer portal, with only open information, need an EV certificate?

Thank you very much.

**Comment by DeiGratia33** [comment]
The server certificates were not specified under the OpenBanking specifications and have the same rules defined by WebTrust and ICP-Brasil. 
FYI: If you select an EV, per Cab/Forum, wildcard is not allowed. You need to interact directly with your CA to see their practice and certificate type you will select.

If your entity does not use any client application, and therefore, it will not authenticate at banks, you will not have an application to be authenticated, and does not require an client certificate.

The intent of EV Certificate, issued out of the ICP-Brasil, was to better interoperability with the end user during the authentication process, not exactly to the developer. But to avoid misunderstanding, please interact with your institution or Open Banking helpdesk to receive a formal interpretation of the Central Bank. This item is attached to the IN99 Resolution.

**Comment by ginglass** [comment]
Hi @DeiGratia33 ,

the main point here is that developer´s portals is out of scope of Open Bankig and it is not so clear on specs. The term "clientes das instituições participantes" specified at 3.14 of IN99 and the obligation of EV cert to any "Sistemas Front-End" could allow some misunderstanding that it is not just for ASPSP´s customers.

I suggest to make a litle change on certificate profile as follows:
https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-certificate-standards-1_ID1-ptbr.md#certificado-para-front-end-certificadofrontend

---
(...)
Front-End certificates are used to provide services, in general web pages, using TLS, which are accessed by the end user. Given their purpose, and to ensure greater interoperability, certificates must be of the EV (Extended Validation) type and must be generated through a valid certificte authority, following the rules defined in RFC 5280 and RFC 2818, in accordance with the principles and WebTrust criteria. 

**This certificate is just needed to provide trust/confidence for end user customers for authentication purpose. Developer's portals are out of scope of Open Banking Brasil specs. Therefore, EV certificates are not needed to provide trust to developer's portals provided by any participant.**

---

portuguese version:

**O certificado EV é necessário para promover a segurança e a confiança do usuário (cliente bancário) no acesso às interfaces (Front-End) de autenticação Portais de desenvolvedores, normalmente com orientações técnicas para promover o desenvolvimento de sistemas com base nas API´s publicadas, estão fora do escopo da especificação de certificados do Open Banking. Portanto, certificados do tipo EV não são obrigatórios para acesso a esses portais.**

---

Do you agree? Can I raise a PR with these informational changes?

Is there anything else @leandrobarra ? 

Regards

--
IN-99 item 3.14:
3.14 Os certificados utilizados para comunicação de sistemas Front-End, acessados diretamente por clientes das instituições participantes, em especial para realizar autenticação, devem ser do tipo Extended Validation (EV) e podem ser emitidos por autoridade certificadora em funcionamento.

**Comment by DeiGratia33** [comment]
Hi @ginglass.


IMHO: We should do something different. This kind of explanation could be included inside of a FAQ.


Or, better yet, I was discussing with some folks to create a table to give a view of where (purpose) each type of certificate would be used. Including things that are not a certificate, such as Key Enc.


What do you think?

**Comment by ginglass** [comment]
Hi @DeiGratia33 

Great suggest, It also could be present in a FAQ.

Unfortunately, public owned companies need a more formal approach, like a spec, to justify it´s decision on buy (or not buy) something. Thats why I suggest inside a section on cetificate specs dedicated to explain details about EV certificates required by IN 99. The same certificate refered by IN99 3.14, whose understanding sounds ambiguous.

We could be more direct as:

**Developer's portals are out of scope of Open Banking Brasil specs. Therefore, EV certificates are not needed to provide trust to developer's portals provided by any participant.**

**Comment by leandrobarra** [comment]
Your information was very enlightening.
Thank you very much.

**Comment by joaorodolfo** [comment]
@DeiGratia33 @ginglass
Im my opinion, we should go for both ways: publish it at the FAQ and include this info at one Table with Certs purpose vs environment.

Before I change it, I will post here to collect some feedbacks.

**Comment by petersonfs** [comment]
Thank you for the information @DeiGratia33 @ginglass. A FAQ would be appreciated by the community.

**Comment by joaorodolfo** [comment]
We preparing a PR to improve it into the new certificate standards version. We can close at this ticket.

**Comment by joaorodolfo** [comment]
We had included a table into Certificate Specs with details. If you have questions, please have a look: https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-certificate-standards-1_ID1-ptbr.md
