### ISSUE TITLE
Suggestion :: Unify guides

### ISSUE THREAD

**Issue by andreborges01** [OpenBanking-Brasil/specs-seguranca#15]
The guides could be unified, as it is useful, even for the development made by ASPSP, to know the details of the `request object` and the flows detailed in the guide for TTP. I think joining these documents would simplify to developers.

**Comment by RalphBragg** [comment]
Awaiting more comments.

**Comment by andreborges01** [comment]
The request is to unify all the documents in only one. Nothing especial related to the "request object"

**Comment by RalphBragg** [comment]
@DeiGratia33 and Erick - the request needs to be taken to the working groups as we were asked to create these as separate guides. There is a lot more actions that a Bank has to perform for example.
