### ISSUE TITLE
Consent Life Cycle Management Not Clear: e.g Cancel Consent - update to rejected?

### ISSUE THREAD

**Issue by samlarsen1** [OpenBanking-Brasil/specs-seguranca#159]
Hi, we have an assumption that when the customer clicks on the 'cancel' button on a consent authorisation screen, the ASPSP is required to update the consent status to 'Rejected'.

We can't find this explicitly in the documentation.  Can you confirm if this is the expected behaviour?

**Comment by RalphBragg** [comment]
@samlarsen1  - i can't comment for the security team but i can confirm that this is the behaviour we are expecting to be implemented in the certification suite. There will be a relying party TPP test to confirm that the TPP deletes any rejected or expired consents when they are no longer needed.

consent life cycle docuementation needs to be improved.

**Comment by alexasensio** [comment]
What about the behaviour on the ASPSPs? Are they expected to change the status to REJECTED? Currently the certification for OpenID Providers (ASPSPs) only fapi1-advanced-final-user-rejects-authentication test that an access_denied response is provided.

In other words: who is responsible for changing the status of the consent when the customer clicks CANCEL: the ASPSP?, the TPP or both?

**Comment by RalphBragg** [comment]
As i understand it, the ASPS should change the status too rejected and the TPP should DELETE the resource.
But i could be mistaken. The UK model was not 100% followed on this point as teh UK modle changed in version 1.8

This isn't documented as far as i can tell

**Comment by ginglass** [comment]
Hi guys, sorry for long delay.

In my opiniuon, both are correct. When a user click on "cancel" on consent page the ASPSP must change status to REJECTED. If a user cancel a consent on TTP (ex., at some consent management page) the TTP must call DELETE method at consent endpoint. So, the ASPSP have to change the status to REJECTED and revoke all related tokens. TTP should remove all related tokens also. A webhook will be described in a near future to improve this mechanism. There is no use case to change a consent. 

If a consent has expired, ASPSP have to return status REJECTED (as an return to GET method at consent endpoint). TTP may use this method do check consent status.

If a consent, due an error condition, for example, is on AWAITING_AUTHORISATION or AUTHORISED and there is no access/refresh_token echanged (miss an authorizes code due a redirect failure, for excample) for more than 60 minutes, it have to be chaged to REJECTED status. Probably a new status value to better represent/describe this situation will be specified soon.

There is more information here (unfortunately is in portuguese):
https://openbanking-brasil.github.io/areadesenvolvedor/#tocS_EnumAccountPaymentsType

**Comment by samlarsen1** [comment]
@ginglass "When a user clicks on "cancel" on consent page the ASPSP must change status to REJECTED"
 - We're having trouble clarifying this point as it doesn't seem to be documented clearly anywhere.  Please can you clarify in the documentation - there is also no conformance test for this.

**Comment by RalphBragg** [comment]
There will be shortly.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RalphBragg** [comment]
This issue has been addressed i believe by including a specific conformance test to drive this scenario. @georgecodes If so I propose it can be closed.

**Comment by georgecodes** [comment]
A user cancelling out of the consent page and resulting in the ASPSP setting the status to REJECTED is indeed covered by a consent API test.

**Comment by MarcusJanuario** [comment]
Right now though, if we just cancel the authorization request instead of going through with it and setting the status to REJECTED what would happen with the conformance test?

We would like to understand how urgent it is for our institution to work on this (since right now we are not doing this), if we can postpone it or not.

**Comment by RalphBragg** [comment]
If it was rejected by the user (and the user was returned to the TPP) if it isn't REJECTED it should fail conformance.

**Comment by RalphBragg** [comment]
This is also a mandatory flow for payments as well, and if the TPP stuffs up the pixPayment request vs the consent.

**Comment by alexasensio** [comment]
Can anyone point to the particular conformance test that is checking this? Is this as part of OIDF tests or functional ones?

**Comment by georgecodes** [comment]
It’s a test module in the consent API functional tests. Specifically; consent-api-status-declined-test

**Comment by RalphBragg** [comment]
This has been addressed and a specific test class checks for the correct migration of consent status's into the correct state.
