### ISSUE TITLE
Question: Nonce and State max &/or min length?

### ISSUE THREAD

**Issue by alexasensio** [OpenBanking-Brasil/specs-seguranca#160]
I have not been able to find any minimum or maximum requirement lengths for the authorization request parameters 'nonce' and 'state'.

Only found out some implementation notes on [OIDC](https://openid.net/specs/openid-connect-core-1_0.html#NonceNotes) or [OAuth2](https://datatracker.ietf.org/doc/html/rfc6749#section-10.12), but nothing specific describing any recommended minimum length or maximum permited.

However, the OIDF Conformance test is checking that the Providers implement some limits on length (see fapi1-advanced-final-ensure-request-object-with-long-nonce and fapi1-advanced-final-ensure-request-object-with-long-state).
* Is there any guidance on the maximum characters to allow for both nonce and state?
* What about mimimum length?

**Comment by RalphBragg** [comment]
https://github.com/openid-certification/oidctest/issues/134

**Comment by RalphBragg** [comment]
Please raise this against the OIDF conformance suite or the FAPI Bitbucket.

**Comment by perlboy** [comment]
I don't believe there is any limit of nonce and state but if it is long it must be accepted and returned properly or rejected with a defined message? 

From the FAPI Suite:

> This test passes a 384 character nonce in the request object. The authorization server must either successfully authenticate and return the nonce correctly, or if it does not support nonces that long it may return an invalid_request error back to the client or show an error page (saying the server rejects long nonce - upload a screenshot of the error page). The server MUST NOT return the nonce corrupted or truncated.


As for minimum length, OIDC says some comments about this:

> Sufficient entropy MUST be present in the nonce values used to prevent attackers from guessing values.


I'm not sure if FAPI suite checks the entropy but if it did I assume it'd be based on the shannon entropy calculations of at least 128bit like other entropy checks.

**Comment by jogu** [comment]
Yes, to confirm, for FAPI certification the requirements are:

1. A 128 character `state` MUST be supported

2. A 384 character `state` MUST be either supported or rejected as too long (i.e. it can't be accepted but then truncated)
