### ISSUE TITLE
Inconsistency on template file signing certificate

### ISSUE THREAD

**Issue by FlavioABrandao** [OpenBanking-Brasil/specs-seguranca#161]
1. The template file "Configuration template for signing certificate - OpenSSL" has an inconsistency because, in the documentation, there is a **date of birth** "otherName (OID 2.16.76.1.3.4 – ICP-Brasil): Responsible for the certificate of legal entity holding the certificate (**date of birth**, CPF, PIS/PASEP/CI, RG)" and in the template does not have this information.
otherName.2 = 2.16.76.1.3.4;UTF8:<CPF/PIS/RF of responsible person>

2. This same file is missing "**:**" in line otherName.1 = 2.16.76.1.3.3;UTF8<CNPJ>

**Comment by DeiGratia33** [comment]
A PR is needed to correct the typo.

**Comment by RalphBragg** [comment]
@ginglass  - any update? If you want someone else (me) to pick it up or even @FlavioABrandao just assign the ticket to them to correct the typo.

**Comment by joaorodolfo** [comment]
I had done the update. We can close this ticket.
