### ISSUE TITLE
Use content-type application/jwt for signed payloads

### ISSUE THREAD

**Issue by mpivaa** [OpenBanking-Brasil/specs-seguranca#166]

**Comment by RalphBragg** [comment]
Hi - the signing mechanism that has been adopted is a detached signature. Which signed payload is sent as a JWT that doesn't have the correct content type?

**Comment by mpivaa** [comment]
@RalphBragg I believe that the security working group voted to not use detached signatures for phase 3.

**Comment by mpivaa** [comment]
Correcting: application/json
