### ISSUE TITLE
Questions: How to generate and use encryption key for JWE

### ISSUE THREAD

**Issue by melothiagort** [OpenBanking-Brasil/specs-seguranca#167]
I understood that the encryption key for the request object is necessary. 

1) So, what are the steps do create this encryption key ? 
2) Should it be created using the Directory ?

I have entered in the directory URL (https://web.sandbox.directory.openbankingbrasil.org.br/organisations) and I have created a Software Statement .
After that I am allowed to create a EncKey.

When I try to upload the CSR to get the CRT, I am receiving the following error

 Certificate Request Validation Error - Cannot parse incoming PEM as RSA Public Key - caused by - class org.bouncycastle.pkcs.PKCS10CertificationRequest cannot be cast to class org.bouncycastle.asn1.x509.SubjectPublicKeyInfo (org.bouncycastle.pkcs.PKCS10CertificationRequest and org.bouncycastle.asn1.x509.SubjectPublicKeyInfo are in unnamed module of loader lambdainternal.CustomerClassLoader @3feba861)

 Example of comand informed by the Directory:
openssl req -new -newkey rsa:2048 -nodes -out a2105f2a-8305-4ad4-bfa4-6c04b960032a.csr -keyout PlPaqy2MYpOZBigDWwdR4X.key -subj "/C=BR/O=Open Banking/OU=5d249486-c697-5295-a856-9955ed3ac332/CN=a2105f2a-8305-4ad4-bfa4-6c04b960032a" -sha256

**Comment by RalphBragg** [comment]
The command on the directory UI is incorrect, it will be addressed shortly. In the meantime you can use this 
openssl genrsa -aes256 -out private.pem 2048
openssl rsa -in private.pem -outform PEM -pubout -out public.pem

**Comment by RalphBragg** [comment]
These instructions were also added to the directory UI.
