### ISSUE TITLE
Public JWE in wrong JWKS URL

### ISSUE THREAD

**Issue by melothiagort** [OpenBanking-Brasil/specs-seguranca#168]
After creating the encryption key for JWKS in the software statement, the enc key is stored in transport.jwks, but I was expecting it in application.jwks

 Here is an example:

https://keystore.sandbox.directory.openbankingbrasil.org.br/5d249486-c697-5295-a856-9955ed3ac332/eb3f76ae-da38-4e94-81f5-5ce1f9f7768b/application.jwks

https://keystore.sandbox.directory.openbankingbrasil.org.br/5d249486-c697-5295-a856-9955ed3ac332/eb3f76ae-da38-4e94-81f5-5ce1f9f7768b/transport.jwks

 Expected result: Enc Key in application.jwks

Result found: Enc key in Transport.jwks

Is this an error in the sandbox directory ?

**Comment by RalphBragg** [comment]
Can you remove this key and readd it. This was a configuration issue with this certificate profile type.

**Comment by RalphBragg** [comment]
Assuming this is closed.
