### ISSUE TITLE
Question: Access Token Generation - Phase 3

### ISSUE THREAD

**Issue by douglasramaldesOA** [OpenBanking-Brasil/specs-seguranca#170]
Hi friends, can you help me with a question, which is related to phase 3 access token generation.

To get the payment scoped access token, would it be basically like this?
`curl --cert transport.pem --key transport.key example/token -X POST -d 'grant_type=client_credentials&scope=payments openid'`

Is anything else needed ?

**Comment by RalphBragg** [comment]
Yes

**Comment by douglasramaldesOA** [comment]
Thank you Ralph,

Can you tell me if there are already tests on `www.certification.openid.net` for phase 3?

**Comment by RalphBragg** [comment]
Yes - however the content types are only JSON payloads.
ID2 of the security profile was only published on friday which marked all of these reqests and responses as needing to be JWTs.

The specification for this was signed off on friday so it'll take a week or so to get the directory, mock bank and both conformance suites setup to send process and validate JWTs as defined by the new specs.

In the mean time there is an example here; https://gitlab.com/openid/conformance-suite/-/wikis/Brazil-Example-Configuration#private_key_jwt-with-payments-api for the OIDF test suite using the JSON payments apis

**Comment by RalphBragg** [comment]
@douglasramaldesOA  - can you close this ticket if you're happy with it.
