### ISSUE TITLE
Question: Do JWS Signing Requirements only apply to Resource Server resources? Answer: Yes.

### ISSUE THREAD

**Issue by dcreado** [OpenBanking-Brasil/specs-seguranca#174]
Hi

the Message Content Signing Considerations of open-banking-brasil-financial-api-1_ID2 requires that iss and aud claims on JWTs requests and responses (I'm assuming here that id token is included as well) to be the organizationID for the issuer and client on the Central Bank Directory.

There are multiple specification that require and recommend those claims to be the issuer URL and client id, in order to implement an effective security on the client and server level without requiring a central authority. One aspect of the central authority is that it makes harder for implementing and debugging scenarios.

Here some conflicts that I can enumerate:

The JARM specification (https://openid.net//specs/openid-financial-api-jarm.html) requires that response iss must be the issuer URL and the aud claim to be the CLIENT ID.

https://openid.net//specs/openid-financial-api-jarm.html - section 4.1
The JWT always contains the following data utilized to secure the transmission:

    iss - the issuer URL of the authorization server that created the response
    aud - the client_id of the client the response is intended for
    exp - expiration of the JWT

The OpenID Connect Core strongly recommend that iss and aud of the a Request Objects to be the client id and the issuer URL respectively. 

The JWT Secured Authorization Requests (or JAR) also recommend the same approach, using the client id and the issuer URL for the iss and aud claims.

The OIDC Discovery state that the issuer URL must be the same as the iss claim of the id token, such that clients can validate the JWT based on the JWK exposed by that issuer.

From OIDC Discovery (https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata)

issuer
    REQUIRED. URL using the https scheme with no query or fragment component that the OP asserts as its Issuer Identifier. If Issuer discovery is supported (see Section 2), this value MUST be identical to the issuer value returned by WebFinger. This also MUST be identical to the iss Claim value in ID Tokens issued from this Issuer. 

I guess the question is why are we centralizing the security of every JWT token on the Central Bank Directory?

**Comment by RalphBragg** [comment]
This alternative was discussed with the security group and rejected in favour of what is currently specified. The purpose of the JWT is not security but non repudiation. 

In the case of Brazil  Open Banking it is an organisation that is assuming responsibility for the 'signature' of the entity, not a client. i.e if it would be contested the court wants to know what legal entity signed it there's no interest in which app. 

The Brazil Certificate Profiles for signing are not bound to a specific application or software. The Brasil ICP specification is only a certificate issued to an organisation NOT to a software record.

These two key items led to this approach being adopted over the one you suggested.

**Comment by dcreado** [comment]
Thanks Ralph,

indeed, there is no conflict with the OpenId Connect Core. But there is a conflict with JARM.
https://openid.net//specs/openid-financial-api-jarm.html - section 4.1
The JWT always contains the following data utilized to secure the transmission:
iss - the issuer URL of the authorization server that created the response
aud - the client_id of the client the response is intended for
exp - expiration of the JWT

I'm not sure how this will be addressed on the RP certification.

If the JWKS are hosted and managed by the directory, that is another aspect of the design.
It is not required for hosting the certificates on the directory to change the iss and audience on the Request Objects and Response Objects to match the identifiers there. For instance: you might have a client id ABCD with its software statement and JWKS endpoint pointing to https://keystore.directory.openbankingbrasil.org.br/12345678/application.jwks. 

I'm afraid that the specification is not matching what is implemented on the products available on the market, and that is not required to be done to implement non repudiation or promptly removing agents from the openbanking ecosystem.

**Comment by RalphBragg** [comment]
Hi,

Again, there is no issue with JARM or any of the openid connect / oauth 2 requirements. The openid foundation and Raidiam are already testing the implementation of this in the oidf conformance suite.

this signing spec does not in anyway change or impact any of these requests.

**Comment by dcreado** [comment]
I think I got it now...
The JWS section does not applies to request and response objects of the FAPI authorization endpoints. Is that correct?
if that is the case, the text needs to be clearer on where does that applies to or suppress the section from ID2 as it implies that **every** JWT requests and responses (including the authorization) are affected.

**Comment by RalphBragg** [comment]
hi - this is correct and yes on second reading it isn't clear. I have a draft pull request to tidy up ID2 from an english language view point. A section for resource server requirements need to be created where this will be refrenced.

**Comment by dcreado** [comment]
ok! now it makes complete sense :)

**Comment by dcreado** [comment]
thank you!
