### ISSUE TITLE
Question: How to register Encryption key for ASPSP (Brazil Directory)

### ISSUE THREAD

**Issue by melothiagort** [OpenBanking-Brasil/specs-seguranca#175]
From ASPSP pont of view, how can I make the public key to encrypt the request object available to the TPP ?

I am creating a software statement in the sandbox directory just to add the EncKey in order to get the KID for the key and make it available in the JWKS.

Is this correct ? I have heard that i shoud not include the public key to encrypt the request object  in the directory.

Is there any documentation for this ?

**Comment by RalphBragg** [comment]
Hi,

Using a specific software statement is the correct way. Don't assign the software statement any regulatory roles.

RB
