### ISSUE TITLE
Broken link in security spec

### ISSUE THREAD

**Issue by samlarsen1** [OpenBanking-Brasil/specs-seguranca#176]
The following section has a space in the url and doesn't resolve, it needs to be updated to remove the space:
https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-financial-api-1_ID2.html#section-6.1-1.3.5.2.1

From this update: https://github.com/OpenBanking-Brasil/specs-seguranca/pull/169/files#diff-03e590260fc79d8a5195187365563c443b685df5f5f555ffaaa96944d61988e7R349

**Comment by joaorodolfo** [comment]
Hi @samlarsen1 please, have a look at the updated docs and let we know if you got some error.

https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-financial-api-1_ID3.md
https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-financial-api-1_ID3.html

Thanks.
