### ISSUE TITLE
Trying to load BRSEAL CSR on Organisation Certificates (Error 400)

### ISSUE THREAD

**Issue by vinnyaju** [OpenBanking-Brasil/specs-seguranca#179]
Hi, i have generated a CSR to load on Directory, but i`m getting an error 400.

Certificate type: BRSEAL EXTERNAL
Error: Certificate Request Validation Error - Could not read certificate object from incoming PEM string - caused by - class org.bouncycastle.pkcs.PKCS10CertificationRequest cannot be cast to class org.bouncycastle.cert.X509CertificateHolder (org.bouncycastle.pkcs.PKCS10CertificationRequest and org.bouncycastle.cert.X509CertificateHolder are in unnamed module of loader lambdainternal.CustomerClassLoader @3feba861)

The same file i tried to load (CSR) i open with the command below and i can see the infos... Not sure what i'm doing wrong.

`openssl req -text -noout -verify -in file_name.csr`

To generate the CSR i used the model at: https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/certificate-generation-instructions/brseal.cnf

**Comment by RalphBragg** [comment]
A BR SEAL external is a certificate sourced from the Brazil PKI. i.e an external certificate authority. You can only use the internal Raidiam PKI by exception only. What you're doing is uploading a CSR to a certificate type that is expecting a Certificate.

**Comment by vinnyaju** [comment]
Thanks for the quick reponse, but i thought i should load csr in the directory and notify my CA with my organisation id so it could sign my csr and upload my certificate directly on directory...

You say i should go directly to my CA with my CSR and it`ll not upload the certificate directly to the directory but provide it to me so i upload on directory?

**Comment by RalphBragg** [comment]
That’s correct, for production, brazil operates a “bring your own certificate” approach where you provide to your CA of choice the cerificate signing request. The ca will validate the software statement ID and organisationId with the directory and issue to you the certificate. You can then upload it, remove it etc at your leisure .

**Comment by vinnyaju** [comment]
Thanks Mr. Bragg, 

One last question about your answer, some CAs are asking for "Software statement ID" to issue the Payload Signature Certificate (BRSEAL), but it's completely useless for this purpose, It only make sense to issue the Client Certificate, named on documentation Transport Certificate (BRCAC), am i correct?

**Comment by joaorodolfo** [comment]
My 2 sec here.

@vinnyaju you are correct. Maybe it's a mistake for some CA professional about the validation process. 

You can notify CA, but, if you have any problem around it, send an email to Security WG, we can manager it into PKI Squad.

**Comment by vinnyaju** [comment]
Thank you @joaorodolfo and @RalphBragg
