### ISSUE TITLE
Update into CERTs Specs // A BR SEAL external is a certificate sourced from the Brazil PKI. i.e an external certificate authority. You can only use the internal Raidiam PKI by exception only. What you're doing is uploading a CSR to a certificate type that is expecting a Certificate.

### ISSUE THREAD

**Issue by joaorodolfo** [OpenBanking-Brasil/specs-seguranca#180]
A BR SEAL external is a certificate sourced from the Brazil PKI. i.e an external certificate authority. You can only use the internal Raidiam PKI by exception only. What you're doing is uploading a CSR to a certificate type that is expecting a Certificate.
CSR = BRSEAL or BRCAC
CERT = BRSEAL_EXTERNAL or BRCAC_EXTERNAL

_Originally posted by @RalphBragg in https://github.com/OpenBanking-Brasil/specs-seguranca/issues/179#issuecomment-903854077_

**Comment by RalphBragg** [comment]
Obviously this applies to production only. Sandbox you can select BRSEAL and upload a CSR.

**Comment by joaorodolfo** [comment]
It will be included  into CERTs SPEC ID2 - Draft in the future.
