### ISSUE TITLE
Registration Access Token Recovery

### ISSUE THREAD

**Issue by RalphBragg** [OpenBanking-Brasil/specs-seguranca#181]
It appears that several banks (acting as TPPs) failed to record or log the client registration access token that should have been issued with the DCR response. Despite the obvious question mark of “how a TPP could get themselves into this situation”? it raises the question as to whether or not the ecosystem needs a mechanism to recover this credential if a TPP somehow forget it.

If this is something that would be of interest to the group then the following options exist to address it ranging from the most “spec compliant” to more bespoke.

1. support rfc7591 Re-registration of a software statement that returns the same clientId. Currently there is no prescribed behaviour across banks for how to handle a Re-registration request. Some banks will accept and re-issue a new client ID, some banks will update an existing registration and other banks will reject the registration.

a simple solution is to require banks to accept as a Re-registration / update a dcr request even if the software is already registered which would return the registration access token to the client to use at the management endpoints. (This is probably the most easiest to implement).

2. Support a signed jwt as an alternative registration access token. A simple jwt issued by client (aud: OP issuer, Iss: clientId, iat, exp, nbf,jti) could be used as an alternative registration access token.

3. Use client credentials grant to obtain an access token from the OP to use as a registration access token.
4. Do nothing, TPPs should know how to look after their credentials including registration access tokens and if they lose them they can either Re-register or attempt to recover then BI-laterally with the openid provider.

Any of the above work.

**Comment by joaorodolfo** [comment]
Guys, for the moment, I believe which it had been improved into DCR Docs and Certification Tests published at the end of last year. 

For the moment, there is no plan to support the Re-registration. 
To solve any problem in flow, the participant should use the ServiceDesk to solve it.

We had created the DCR functional tests to solve the gaps in the ecosystem. But feel free to send some improvement ideas.
