### ISSUE TITLE
Question: Message Content Signing

### ISSUE THREAD

**Issue by esachser** [OpenBanking-Brasil/specs-seguranca#184]
Hi,
About the message signing, present on consents (for payments) and payments APIs, we've run into some questions.
1. Will there be some rule about how to validate `iat`claim? For example, in DCR process, the SSA must have been created at maximum 5 minutes in the past.
2. Will there be some rule about how to validate `jti` claim? How does it relates to the idempotency key? If there is no validation, or rule, is that claim needed? Just validating if is an UUID v4 seems not enough...

**Comment by joaorodolfo** [comment]
@esachser please have a look into: https://us5.campaign-archive.com/?u=49f5ff8910ce85bdb1d9a7864&id=db99e2d5c2
There are instructions about JTI. 

Please, if you have more question, could you open a ticket into OpenBanking Brazil service desk when someone can cat you question and reply quickly? 

Thanks.

**Comment by joaorodolfo** [comment]
@esachser please have a look into: https://us5.campaign-archive.com/?u=49f5ff8910ce85bdb1d9a7864&id=db99e2d5c2
There are instructions about JTI. Please, if you have more question, could you open a ticket into OpenBanking Brazil service desk to some one cat you question and reply quickly?
