### ISSUE TITLE
Question: As a ASPSP where do i get the tpp logo uri? 

### ISSUE THREAD

**Issue by c0dc0d** [OpenBanking-Brasil/specs-seguranca#189]
To get the TPP's  LogoUri the https://openbanking-brasil.github.io/areadesenvolvedor/documents/OpenBanking-Guia_Operacao_Diretorio_Central.pdf show the ASPSP have to have an SST and a transport key to execute the client credentials flow.

 

Is that correct? Is there another way to get this piece of information?

**Comment by RalphBragg** [comment]
the logo_uri is included on the software statement assertion. OP's should just set it on registration.

**Comment by RalphBragg** [comment]
Accepted Answer: The TPPs logo uri is included on the software statement assertion. If a TPP wishes to update this at a Bank they should use RFC7592 that all banks are required to support to update the client at the bank.

**Comment by melothiagort** [comment]
Hello, Ralph. I think I did not understand the whole process. The operational guide (https://openbanking-brasil.github.io/areadesenvolvedor/documents/OpenBanking-Guia_Operacao_Diretorio_Central.pdf), page 90, in step 1, indicates that a BRCAC certificate (client certificate, from 5.2.2 --> https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-certificate-standards-1_ID1.html) must be uploaded in the SS. So, the ASPSP should buy a certificate with a C.A just to obtain the TPP logo ? This does not make any sense to me. Am I missing something ?

**Comment by RalphBragg** [comment]
Hi,
No the bank doesn't have to buy a certificate to obtain the tpp logo. Look at the ASPSP end to end user guide. https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-dynamic-client-registration-1_ID1-ptbr.md 

A TPP presents this SSA to the Bank which is signed by the directory https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-dynamic-client-registration-1_ID1-ptbr.md#reinvidica%C3%A7%C3%B5es-da-declara%C3%A7%C3%A3o-de-software-claims--claims

One of the claims is the logo of the tpp's application.   "software_logo_uri": "https://www.raidiam.com/accounting/logo.png",
