### ISSUE TITLE
BCB Manuals

### ISSUE THREAD

**Issue by andreborges01** [OpenBanking-Brasil/specs-seguranca#19]
References to BCB manual´s should be present in these documents.

https://www.bcb.gov.br/estabilidadefinanceira/exibenormativo?tipo=Instru%C3%A7%C3%A3o%20Normativa%20BCB&numero=99

https://www.bcb.gov.br/estabilidadefinanceira/exibenormativo?tipo=Resolu%C3%A7%C3%A3o%20Conjunta&numero=1

**Comment by RalphBragg** [comment]
Hi - feel free to propose a pull request for the text and where it should go.

**Comment by RalphBragg** [comment]
A reference to the security manual was added to the security provisions for information however there is nothing explicit in the manual that would override the requirements set in FAPI Advanced.
