### ISSUE TITLE
Should we require the accept header for signed API's

### ISSUE THREAD

**Issue by bruno-ortizgb** [OpenBanking-Brasil/specs-seguranca#190]
In the fourth item of this [section](https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-financial-api-1_ID2.md#message-content-signing-considerations-jws-jws) of the security profile, it is stated that:
`The HTTP content-type of requests and responses with JWS messages shall be defined as: "application/jwt".`

shouldn't we require that the [accept header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) should be sent as "application/jwt" by the clients that wish for a signed response?

**Comment by RalphBragg** [comment]
Hi - this isn't quite as straight forward. If a TPP requests application/jwt however they screw up their JWT or a bank can't process it then they will get a application/json response type back. If they specify a content type and don't specify that they can handle both then an interpretation is that the bank should return an 'invalid content type' which is less than ideal.

It would be better that TPPs are required to specify none or specify that they support both. There is no 'negotiation' of the response type availabel for this response. A bank must always return these as JWTs.

**Comment by RalphBragg** [comment]
this ticket should be transferred to the specifications git.

**Comment by joaorodolfo** [comment]
It will be sent to GT Specs.
