### ISSUE TITLE
Question: Which endpoints must allow cpf and cnpj claims in phase 3?

### ISSUE THREAD

**Issue by ranierimazili** [OpenBanking-Brasil/specs-seguranca#191]
Hello,

I'm implementing phase 3 endpoints (payments) and I'm not sure where I need to allow the usage of cpf and cnpj claims as defined in the sections 5.2.2.2 and 5.2.2.3 of the [security spec](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-financial-api-1_ID2.html).

For phase 3 endpoints, I think it makes sense to be available only at consent creation method (POST /payments/v1/consents) because after that the TPP will redirect to the ASPSP and if the user approves the consent the TPP will receive the code (to exchange by an access token and this access token can be used on userinfo endpoint to get the requested claims) and an id_token (where the request claim can be returned).

Considering this... 
**Claims should not be permitted at:**

- GET /payments/v1/consents/{consentId}
- POST /payments/v1/pix/payments
- GET /payments/v1/pix/payments/{paymentId}

Because the methods above doesn't have a end user interaction to discover their cpf/cnpj. 
 
**Claims should be permitted at:**

- POST /payments/v1/consents

Because the method above needs the approval of the end user, so it's possible to get their cpf/cnpj.

Is my understanding right about the specification?

**Comment by alexasensio** [comment]
Claims requests are to be supported only in the authorization request endpoint. See some examples at the [TPP User Guide](https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/tpp-user-guide.md#431-create-openid-connect-request-object).

Additionally, the POST /payments/v1/consents endpoint does not require the approval of the end-user. Is just a back-end to back-end call with no customer authentication.

**Comment by ranierimazili** [comment]
@alexasensio thanks for the support.
