### ISSUE TITLE
Reference Update: PAR has been given an RFC 9126 

### ISSUE THREAD

**Issue by RalphBragg** [OpenBanking-Brasil/specs-seguranca#193]
Normative references should be updated in all specifications

**Comment by joaorodolfo** [comment]
@RalphBragg did you know if there are some big changes into RFC or is it only a final version of the old RFC:(https://tools.ietf.org/html/draft-ietf-oauth-par)?

Thanks

**Comment by michellebandarraChicago** [comment]
Reunião do GT Segurança de 17/03/2022: Grupo debateu entendimento sobre o tema, chegando à conclusão de que não há impactos das mudanças da RFC 9126 na documentação PAR, portanto a issue pode ser finalizada
