### ISSUE TITLE
Rotation of RFC7592 registration_access_token

### ISSUE THREAD

**Issue by jogu** [OpenBanking-Brasil/specs-seguranca#198]
RFC7592 defines a mechanism that allows the authorization server to issue a new registration_access_token, invalidating the old one.

For similar reasons to refresh token rotation ( https://github.com/OpenBanking-Brasil/specs-seguranca/issues/129 ) there is the potential for the client to end up with zero working registration_access_tokens (with the additional problem that the client might be unaware of the potential for rotation).

Given the token is presented alongside an MTLS client certificate, and I believe can also only be used for write operations if a recently issued SSA is provided, the security reasons for rotating seem fairly limited and it would seem best not to rotate - particularly if there is no mechanism for dealing with lost registration access tokens (as per https://github.com/OpenBanking-Brasil/specs-seguranca/issues/181 ).

**Comment by RalphBragg** [comment]
@travisspencer - it already was and the current votes based on the fapi ticket is to discourage its use in a fapi 2.0 profile. Given brazil is based on fapi 1 which is final it is completely appropriate for brazil in their profile to disable it.

@jogu - it’s a duplicate ticket.

**Comment by ranierimazili** [comment]
The final decision is to not allow rotation the registration_access_token as published on [OpenBanking Informa #81](https://us5.campaign-archive.com/?u=49f5ff8910ce85bdb1d9a7864&id=db99e2d5c2). 
So I think this issue can be closed.
