### ISSUE TITLE
PKCE requirements

### ISSUE THREAD

**Issue by andreborges01** [OpenBanking-Brasil/specs-seguranca#20]
Security Profile must explain in a short sentense PKCE requirement and which cyber risk it mitigates.

**Comment by RalphBragg** [comment]
The security profile is a profile of OpenID FAPI Advanced Final. As it says in the notes, it is expected that all implementers have read that profile and understand it. This profile does not replace the underlying security specification. 

A requirement to read (and understand) PKCE is included in the tpp end2end user guide.
https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/tpp-user-guide.md#433-obtaining-access-token-via-authorization-code-exchange

PKCE is RFC6736 which is mentioned several times in the specification. 

OAuth 2.0 public clients utilizing the Authorization Code Grant are
   susceptible to the authorization code interception attack.  This
   specification describes the attack as well as a technique to mitigate
   against the threat through the use of Proof Key for Code Exchange
   (PKCE, pronounced "pixy").

I believe this is more than sufficient in the same vein that explaining what FAPI is and what it mitigates is explained in the FAPI specification not in the profile created for a specific implementation.

**Comment by RalphBragg** [comment]
No updates or comments - closing.
