### ISSUE TITLE
Encrypted request objects only required if not using par.

### ISSUE THREAD

**Issue by RalphBragg** [OpenBanking-Brasil/specs-seguranca#200]
Clause 8 of the dcr specification could do with tidying up.

shall require encrypted request objects as required by the Brasil Open Banking Security Profile;

“as required by the Brasil security profile”, which only requires encrypted request objects if not using PAR”.

this clause should be amended to 

If not requiring the use of PAR, shall require encrypted request objects as required by the Brasil Open Banking Security Profile;

**Comment by michellebandarraChicago** [comment]
Hi @RalphBragg , Could you confirm if this issue has been addressed by the new release of the DCR document?
Thank you

**Comment by joaorodolfo** [comment]
It will be sent to backlog into Security WG. Thanks.
