### ISSUE TITLE
JTI lifetime x idempotency-key lifetime

### ISSUE THREAD

**Issue by ranierimazili** [OpenBanking-Brasil/specs-seguranca#209]
At [OpenBanking Informa #81](https://us5.campaign-archive.com/?u=49f5ff8910ce85bdb1d9a7864&id=db99e2d5c2) a lifetime for JTI reutilization was defined (86400 seconds). 
I think the same should be defined for x-idempotency-key because it's another key that can be reused by institutions and keep the history of all x-idempotency-key in a database to query against it can be a very slow task for institutions that has milions of transactions per day.

**Comment by michellebandarraChicago** [comment]
@OpenBankingBrasil-GtEspecs

**Comment by joaorodolfo** [comment]
It will be sent to GTSpecs.
