### ISSUE TITLE
DCR image in dark mode

### ISSUE THREAD

**Issue by andreborges01** [OpenBanking-Brasil/specs-seguranca#21]
DCR image flow is not well exibit when in github dark mode.

**Comment by RalphBragg** [comment]
The images are rendered as SVG which is the only format that the IETF xml2rfc specification supports. The output is intended to be the HTML versions. I will put it on the backlog to re-render the images with an explicit white background.

**Comment by RalphBragg** [comment]
as agreed with the publishing team the HTML documents will be referenced on github pages. This is white mode only. Closing as not required.
