### ISSUE TITLE
Question: How to generate Server certificate for Sandbox

### ISSUE THREAD

**Issue by balasubhramanian** [OpenBanking-Brasil/specs-seguranca#218]
I am able to create BRCAC & BRSEAL CSR & upload to sandbox. Able to make api calls to directory api using BRCAC certificate downloaded from sandbox.

Now for supporting mTLS, I need to install certificate given by ICP Brazil in my server. Please help on the step to generate server certificate.

**Comment by joaorodolfo** [comment]
For ICP webssl certs, you should look at the Certs Specs in: https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-certificate-standards-1_ID1.md.

If you are an openbanking brazil participant, you are able to open some ticket into servicedesk as well:
https://openbanking-brasil.github.io/areadesenvolvedor/#suporte-ao-desenvolvedor
