### ISSUE TITLE
Can DCR be performed multiple times with same client (software_statement) on the same server (participant)?

### ISSUE THREAD

**Issue by ranierimazili** [OpenBanking-Brasil/specs-seguranca#223]
Hello,
I'm testing the DCR against other participants (sandbox) and I could see that on some of them, after register my client and gain a client_id, if I try to register again instead of receive a new client_id I receving an error (HTTP 400).
The messages I've have receving until now are:

```
{
    "error": "invalid_client_metadata",
    "error_description": "Client metadata invalid"
}
```
or 

```
{
    "error": "invalid_request",
    "error_description": "Client(_id) value could not be persisted"
}
```

The tests above were done using private key... I've tried other tests using MTLS and on that participant I could execute the DCR multiple time with the same software_statement.

What's the expected behavior? Maybe a new test on DCR suite could be added to validade the right behavior.

**Comment by ranierimazili** [comment]
@EkkeErick first, thanks for your reply...
In my opinion, it should be permitted to execute multiple DCR with the same data, and here I'm applying the same concept of the rotation of the registration_access_token.

Why the rotation of the registration_access_token was prohibited? Because if on an update you miss the response, you'll lose the token to update your client.

What if you trigger the DCR flow and for some reason you lose the connection? You'll lose the response and will not be allowed to execute the DCR again.

That's exactly what's happening now on my tests as ITP... I'm executing tests agains other TPP's and I wasn't saving the first response... Now the solution is create a new software_statement, but it's a workaround in my opinion.

Hope you consider this when discussing this subject with the security WG.

Thanks

**Comment by joaorodolfo** [comment]
Hi @ranierimazili and @EkkeErick, 
Can I share some docs to provide the current guidance?
DCR / DCM Specs: https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-dynamic-client-registration-1_ID2-ptbr.md
DCR/DCM Swagger Example: https://raw.githubusercontent.com/OpenBanking-Brasil/specs-seguranca/main/dcr_review/dcr-dcm-swagger.yaml

Into both documents, the Security WG had specified a DCR to register and DCM flow to support client updates (brand info or any new SSA version, for example); for this reason, TTP need's to use the correct HTTP method considering the actual specs.

Just to be helpful into Security WG, shay, I ask a question? 
If the docs have RFC 7591 and RFC 7592 linked into specs, what kind of detail do you suggest for the Security WG to improve this doc? - Any examples will be helpful.

About the rotation of the registration access token, the Banks can or not rotate it. Follow this part of Specs: https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-dynamic-client-registration-1_ID2-ptbr.md#manuten%C3%A7%C3%A3o-de-cliente---get-register---put-register---delete-register-get-put-delete

It is the reason why the DCR / DCM tests should verify the correct registration access token rotation. 

Guys, the security WG is still open to any other WG, or TTPs/Banks explaining or suggesting any change/improvement. So please, if you like to discuss it with security WG, let me know, we can have a chat and arrange it.

**Comment by ranierimazili** [comment]
@joaorodolfo about the rotation of the registration_access_token, my fault... the specification kept the understanding that it can be rotated... thanks.

However I still think that DCR should allow multiple calls for the same client, because in case of missing the response, the only option should be create a new software statement, what can't be impractical in a production environment.

Do you see another way in case of missing the response that doesn't require a new software statement?

**Comment by joaorodolfo** [comment]
@ranierimazili may be, there are cases when a bank using a multiple brand. Someone had talked about it into security WG but for the moment, there are no new direction to support it. 

Please if you see any scenario with you will need it, could you notify the securty wg to talk about it? Thanks
