### ISSUE TITLE
CIBA Credit Proposition Timeout and Expiration Timeout

### ISSUE THREAD

**Issue by DeiGratia33** [OpenBanking-Brasil/specs-seguranca#224]
For CIBA (Credit Proposition) it would be necessary to adjust the specification to include:

a) The credit proposal identification generated by the EPOC entity.
Even with the total hint/hint_numbers,  would be appropriate to include an identification of the credit proposal generated by the EPOC. This identification would solve cenarios where the user could go to more than one EPOC and ask for proposal, and without identification of the origin of the request the back could be confused and generate the consent for the wrong request.

b) Include the timeout for the CIBA requests from IFs
It is necessary to specify for how long the Bank must wait for all requests from IFs before send the user the notification of pending approvals.

c) User authentication timeout
Necessary to include the maximum time a user has to approve the consent after notification is sent.

**Comment by pedro-octavio-andrade** [comment]
O fluxo de iniciação de pagamento com CIBA não prevê uso de login_hint. Esse trecho voltará a especificação quando o grupo voltar a discutir a especificação de EPOC
