### ISSUE TITLE
Inconsistencies between `.README` and HTML specs page

### ISSUE THREAD

**Issue by galenodemelo** [OpenBanking-Brasil/specs-seguranca#225]
Recently, we noticed some differences while reading the `.README` file and the website version of these specs.

An example occurred when we were planning to configure the _refresh token_ rotation (since it's a valid way to make them last more), and we didn't see, [on the site](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-financial-api-1_ID3.html) anything prohibiting this.

But, when a colleague looked for the same thing on `.README`, [he found this](https://github.com/OpenBanking-Brasil/specs-seguranca/pull/215), which is more recent than the page (the webpage publishing date says September 27th, and the PR was issued on November).

Being that it didn't refresh the HTML version, I'd suggest shutting down the HTML version and redirecting the users to this repo, guaranteeing that everyone will access the updated spec.

**Comment by joaorodolfo** [comment]
Hi @galenodemelo thanks for the heads up. I will send it to Security WG.
