### ISSUE TITLE
Padrão DCR/DCM HTML - Desatualizado frente ao MD

### ISSUE THREAD

**Issue by joaorodolfo** [OpenBanking-Brasil/specs-seguranca#244]
Pessoal, após ao comunicado abaixo, foi enviado um link HTML onde não é apresentado as mudanças.
https://us5.campaign-archive.com/?u=49f5ff8910ce85bdb1d9a7864&id=5b8dd65a15

Apenas o arquivo MD em PT-BR, apresenta as mudanças, HTML em PT-BR e Padrão em inglês não reflete as mudanças.

@michellebandarraChicago @pedro-octavio-andrade

**Comment by pedro-octavio-andrade** [comment]
@joaorodolfo Obrigado, GT Segurança já mapeou a questão e temos voluntário realizando ajuste da documentação em inglês.
