### ISSUE TITLE
Extended Key Usage validation while uploading brcac.csr file

### ISSUE THREAD

**Issue by mvmosouza** [OpenBanking-Brasil/specs-seguranca#251]
I am getting this error uploading brcac.csr generated file

"Extended Key Usage validation failed, could not find Server Auth purpose 400"
![erro_certificado_open_banking](https://user-images.githubusercontent.com/109555233/179622674-90dcf19f-e7ba-47de-96cb-6bf95fcd53b4.png)

This was already appointed with issue #192 

Now is not working anymore.

**Comment by duilioandrade** [comment]
it worked as follows 

extendedKeyUsage = clientAuth, **serverAuth**

**Comment by ErickRaidiam** [comment]
We are going to have a new Deployment on Sandbox Directory Tomorrow to exclude this validation as it's non mandatory that the server has the serverAuth
