### ISSUE TITLE
Should we add additional verifications to the DCR flows?

### ISSUE THREAD

**Issue by alex-siqueira** [OpenBanking-Brasil/specs-seguranca#28]
The transport certificates issued by ICP-Brasil hold custom attributes that authorization servers could use to cross-check the DCR / SSA request information. For example:

- software statement ID
- participant code

Since ICP Brasil checks these attributes in the Directory, I think we could improve the security of the DCR by checking if they match the values provided by the client in the DCR request.

**Comment by RalphBragg** [comment]
Banks really should just ignore all values from the outer request that they can and extract the attributes necessary from the SSA. There are some attributes that you can't do that without. I can include an extra 'should' clause

**Comment by RalphBragg** [comment]
Additional Clause Added.

**Comment by RalphBragg** [comment]
@alex-siqueira  - can you close this if the update is sufficient.
