### ISSUE TITLE
CIBA spec needs more detail has to how cnpj / cpf claims are requested by client

### ISSUE THREAD

**Issue by jogu** [OpenBanking-Brasil/specs-seguranca#286]
The BR CIBA spec says:

```
3. shall support the oidc standard claim "cpf" as defined in clause 5.2.2.2 of [FAPI-BR]
4. shall support the oidc standard claim "cnpj" as defined in clause 5.2.2.3 of [FAPI-BR] if providing access to resources where the resource owner is not a `natural person`
```

however the underlying CIBA spec provides no mechanism for requesting these claims, as OIDC claims are not directly supported.

https://openbankinguk.github.io/read-write-api-site3/v3.1.10/profiles/read-write-data-api-profile.html#identifying-the-consent-to-be-authorised solves a similar issue of passing the UK intent id by defining a custom member of the CIBA request instead.

**Comment by pedro-octavio-andrade** [comment]
Inclusão de claims de identidade será esclarecido no manual de implementação.
