### ISSUE TITLE
CIBA spec contains two "TODO"s

### ISSUE THREAD

**Issue by jogu** [OpenBanking-Brasil/specs-seguranca#287]
The Brazil CIBA spec has two unfinished sections marked with TODOs:

> Participants shall support all security considerations specified in clause TODO and all sub clauses of [FAPI-BR] and [FAPI-CIBA]

and:

> Participants shall support all data sharing considerations specified in clause TODO of [FAPI-BR]

**Comment by pedro-octavio-andrade** [comment]
Retirar da documentação

**Comment by pedro-octavio-andrade** [comment]
Participants shall support all security considerations specified  in all clauses and sub clauses of [FAPI-BR] and [FAPI-CIBA]
