### ISSUE TITLE
CIBA spec: Provide more guidance on binding_message

### ISSUE THREAD

**Issue by jogu** [OpenBanking-Brasil/specs-seguranca#289]
The Brazil CIBA spec requires a binding_message to be used in some place.

It does not contain any definition of what an acceptable binding message is, for example minimum length or allowed character set.

For interoperability purposes, the spec should probably set out a minimum expectation, or make it clear this is allowed to vary between banks (in which case each bank should be required to document the binding message rules it applies).

**Comment by pedro-octavio-andrade** [comment]
Será incluso no manual de implementação
