### ISSUE TITLE
CIBA spec: flow involving QR codes would benefit from an introductory sentence or two

### ISSUE THREAD

**Issue by jogu** [OpenBanking-Brasil/specs-seguranca#291]
The QR code mechanism is not really explained. A flow diagram or an introductory sentence of two would be helpful; something along the lines of "This flow involves the client making a CIBA request and then presenting an encrypted QR code that contains the `auth_req_id` returned from the AS. The user is told to open their mobile banking app and scan the QR code."

**Comment by pedro-octavio-andrade** [comment]
O manual de implementação contém a introdução sobre o fluxo CIBA

**Comment by marcusalmgren** [comment]
@pedro-octavio-andrade, quando está a dizer "manual de implementação", qual é o documento que está a referir? Se puder fornecer um link, agradecia muito, obrigado.
