### ISSUE TITLE
Registering an Application flow 

### ISSUE THREAD

**Issue by DeiGratia33** [OpenBanking-Brasil/specs-seguranca#30]
Third Party Provider End To End User Guide
1.0 Registering an Application
	- Only the transport certificate will be unique by Application.
	- Remove the ICP-Brasil certificate request process, this is done out of the flow. For the ICP-Brasil, as production, need to include a step where the entity will upload the certificate and associate it with the application. The Login ICP from the TTP is not realistic, it is more like an out-of-band where the TPP goes to any ICP-Brasil CA he wants and buy the certificate.
	- I am not sure we need to include the ICP-Brasil validation step in this document, what it need to be clear to the tpp is the required attributes that are gotten from the directory such Participant Code and Software Statement ID.

**Comment by DeiGratia33** [comment]
The issue is still valid because of the diagram. There is not such thing as ICP Login. The best way to simplify this is to remove the validation steps done by the CAs and include just a step to request the certificate to CA and validate attributes.

**Comment by joaorodolfo** [comment]
I sent it to Backlog of WG-Security.
