### ISSUE TITLE
Obtaining Access to Customers Resources

### ISSUE THREAD

**Issue by DeiGratia33** [OpenBanking-Brasil/specs-seguranca#33]
Third Party Provider End To End User Guide
Only CAs below ICP-Brasil supports OCSP, the root only operates CRL.

**Comment by RalphBragg** [comment]
Will be corrected in the next draft.

**Comment by DeiGratia33** [comment]
3.0 Registering the application with a provider

At this section.

We need to clarify the ICP-Brasil as a chain, not as single entity, this way we clarify that certificates need to me checked using OCSP or CRL as provided by CAs.

This is a thing that needs to be changed at the diagram.

**Comment by joaorodolfo** [comment]
Fixed. From https://www.websequencediagrams.com/files/render?link=1Xqm7oHVrWJ0Ya34s9kdzG1kHpwLobAftNdQHHvf44ikYZadVrou8iFhiFC9pSMP to the actual image into TTP guide.
