### ISSUE TITLE
Question: Does the Directory Authorisation Server Support both private_key_jwt and tls_client_auth? 

### ISSUE THREAD

**Issue by DeiGratia33** [OpenBanking-Brasil/specs-seguranca#34]
Question: The Open Banking Brasil security profile supports both private_key_jwt and tls_client_auth but only tls_client_auth is shown in the "Registering an application with a provider" section of the TPP User Guide. Does the Directory Authorisation Server support it?

**Comment by RalphBragg** [comment]
Yes the directory AS does support it however by default it uses tls_client_auth. A single software on the direcotyr will be used by a TPP that will need to interact with banks that operate both tls_client_auth and private_key_jwt so TPPs will need to support both. 

tls_client_auth for directory interactions is simple and a transport certificate is all that is required

**Comment by RalphBragg** [comment]
Added to FAQ Closing.
