### ISSUE TITLE
Consent's creation omitted data

### ISSUE THREAD

**Issue by josenogueiradalmeida** [OpenBanking-Brasil/specs-seguranca#36]
Hi!

In the [Consent's creation](https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/tpp-user-guide.md#42-creating-consent), I was expecting additional identification data as below ...

"loggedUser": {
      "document": {
        "identification": "11111111111",
        "rel": "CPF"
      }
    },
    "businessEntity": {
      "document": {
        "identification": "11111111111111",
        "rel": "CNPJ"
      }
    }

... but I have found only the following ...

{
  "data": {
    "permissions": [
      "ACCOUNTS_READ"
    ],
    "expirationDateTime": "2021-05-21T08:30:00Z",
    "transactionFromDateTime": "2021-01-01T00:00:00Z",
    "transactionToDateTime": "2021-02-01T23:59:59Z"
  }
}

I suppose this was intentionally ommited for brevity.

**Comment by RalphBragg** [comment]
No - the consent API is currently undergoing review with a recommendation not to include identity data in this way as it is already part of ODIC.

**Comment by RalphBragg** [comment]
Still pending commentary from the security working however making assumption now in the interest of time that Consent API will not be altered.
