### ISSUE TITLE
Questions: Where can i find instructions on generating a BRCAC and BRSEAL Sandbox Certificate?

### ISSUE THREAD

**Issue by DeiGratia33** [OpenBanking-Brasil/specs-seguranca#38]
We need the information on how entities could obtain certificates from Sandbox for non-production environments and where to find the CRL for it.

**Comment by RalphBragg** [comment]
This will be included in the ASPSP User Guide. Obviously the CRL and OCSP endpoints are found in the x509 certificate and OCSP endpoints.

**Comment by RalphBragg** [comment]
The certificate instructions, example openssl configuration files and a shell script with the openssl commands have been added to this repo.
