### ISSUE TITLE
Question: Where do I discover authorization servers for non-public resource offering information

### ISSUE THREAD

**Issue by christianbalz** [OpenBanking-Brasil/specs-seguranca#39]
In tpp-user-guide, item 2.2 Discovering Banks Authorization Servers mentions how to retrieve a list of all participants and their authorization servers for the public context.

Discovery for authorization servers for non-public information should occur through the API /organisations and /organisations/{OrganisationId}/authorisationservers?

**Comment by RalphBragg** [comment]
That's correct - the tpp user guide and aspsp user guides are not finished (by a long shot).

**Comment by joaorodolfo** [comment]
@christianbalz, please, let we know if you have any text suggestion to improve the TTP user guide. If you have, could you please send it to: gt-seguranca@openbankingbr.org. Thanks!
