### ISSUE TITLE
Onde achar o bundle da nova CA do sandbox: Open Finance sandbox Issuing CA - G2

### ISSUE THREAD

**Issue by devops-cora** [OpenBanking-Brasil/specs-seguranca#416]
Ao renovar os certificados BRCAC e BRSEAL, eles são gerados pelo novo issuer **Open Finance sandbox Issuing CA - G2**, onde encontro o bundle dessa nova raiz certificadora?

Obrigado

**Comment by mdjunior** [comment]
Oi, os links para a nova CA foram enviados no Informe 406 e publicados no https://github.com/OpenBanking-Brasil/specs-directory.

Raiz: root-ca.pem
Intermediário: issuer-ca.pem
