### ISSUE TITLE
Reduce unused references

### ISSUE THREAD

**Issue by DeiGratia33** [OpenBanking-Brasil/specs-seguranca#42]
Reading the specification over the documents we are using a lot of reference that are not used for specification and could cause confusions to developers.

For example, if we are not using JARM or PAR, they should be removed.

**Comment by RalphBragg** [comment]
JARM is supported and allowed FAPI Final as is PAR. Banks don't have to support it though but they shouldn't be banned from supporting it nor should they compel clients to use it.

This enables easier migration to FAPI 2.0 Which is due to be published shortly.

**Comment by DeiGratia33** [comment]
The concern here is the questions raised.

When people reads the reference, they have questions if is implemented over the specifications or not.

**Comment by RalphBragg** [comment]
I'm confused, if it is implemented it is advertised on each banks well known configuration endpoint.
e.g https://auth.sandbox.directory.openbankingbrasil.org.br/.well-known/openid-configuration

response_modes_supported":["form_post","fragment","query","jwt","query.jwt","fragment.jwt","form_post.jwt"]
In this case we support JARM and are advertising that we do if a TPP wants to use it.

Likewise "pushed_authorization_request_endpoint":"https://auth.sandbox.directory.openbankingbrasil.org.br/request
we are advertising that we are supporting PAR if a TPP wanted to use it.

**Comment by DeiGratia33** [comment]
I have sent a pull request to create a FAQ to answer these kind of questions.

**Comment by RalphBragg** [comment]
Perfect - using a FAQ is a great way to do this.
