### ISSUE TITLE
Header details

### ISSUE THREAD

**Issue by andreborges01** [OpenBanking-Brasil/specs-seguranca#48]
Documentation could include header details as shown in UK docs

E.g: https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/read-write-data-api-profile.html#headers

**Comment by RalphBragg** [comment]
The FAPI mandatory headers are included in the FAPI Specification. I agree with you, the resources should be articulating all required headers for accessing resources. This isn't part of the security specifications but part of the functional API. How do we get this ticket transferred to the functional API team?

**Comment by RalphBragg** [comment]
Functional specification request. No additional headers are defined as part of the security profile apart from those included in vanilla FAPI Final

**Comment by RalphBragg** [comment]
@GisAlmeida @GislaineAlmeida  - do you believe this can be closed as there is sufficient header information on the funcitonal APIs?

**Comment by GislaineAlmeida** [comment]
> @GisAlmeida @GislaineAlmeida - do you believe this can be closed as there is sufficient header information on the funcitonal APIs?

So Ralph we have some headers detailed in APIs specs.
But not all of them.
For example, version and retry are not included in the specs but the documentation at Developer's Portal makes some references. We need talk about this urgently with the working group.

**Comment by DeiGratia33** [comment]
The fapi headers are included in the specifications of each API. In my opnion we can close this issue.
