### ISSUE TITLE
dynamic consent scope definition

### ISSUE THREAD

**Issue by andreborges01** [OpenBanking-Brasil/specs-seguranca#49]
Reference: https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-financial-api-1_ID1.md#dynamic-consent-scope-definition

at Dynamic Consent Scope Example in the above document, where bancoex does it come from? consent:urn:bancoex:C1DD33123

In the swagger, consentId pattern attribute has different pattern than what is shown in Dynamic Consent Scope Definition. Could you please verify?

**Comment by RalphBragg** [comment]
It's recommended that the ConsentID is name spaced for uniqueness and security - but depending on the outcome of todays discussions this may need to be changed.
