### ISSUE TITLE
open-banking-brasil-financial-api doc foreword 

### ISSUE THREAD

**Issue by josenogueiradalmeida** [OpenBanking-Brasil/specs-seguranca#56]
Hi,

Consider the "open-banking-brasil-financial-api-1_ID1.html" document, Foreword section. It says:

"The Open Banking Brasil Initial Structure is responsible for creating standards and specifications necessary to meet the requirements and obligations of the Brasil Open Banking Legislation as originally outlined by the Brasil Central Bank. There is a possibility that some of the elements of this document may be the subject to patent rights. OBBIS shall not be held responsible for identifying any or all such patent rights.

Open Banking Brasil Financial-grade API Security Profile 1.0 consists of the following parts:

Open Banking Brasil Financial-grade API Security Profile 1.0
[Open Banking Brasil Dynamic Client Registration Profile 1.0][OBB-FAPI-DCR]"

A simple suggestion is to Replace "OBBIS" by "Open Banking Brasil Initial Structure (OBBIS)".

Then, I would like to confirm whether "Open Banking Brasil Financial-grade API Security Profile 1.0 consists" in two parts: itself and DCR Profile, is it correct?

Thanks!

**Comment by RalphBragg** [comment]
that is correct - the security profile for DCR describes who and how you onboard clients. i.e the WHO part of the profile. The security profile describes the HOW.

I will be creating the ID2 version of the specifications shortly and you can raise a PR for the wording change. 

ID1 is locked and out for implementers to implement against. All bug reports and editorial comments will go into ID2 which probably won't be published until end of July unless there are blocking issues found with ID1.

**Comment by DeiGratia33** [comment]
The OBBIS is part of the symbols and abbreviations, I am not sure we need to refer to its full name.

**Comment by RalphBragg** [comment]
Closing as requested.
