### ISSUE TITLE
Consent life cycle

### ISSUE THREAD

**Issue by carlosaaf** [OpenBanking-Brasil/specs-seguranca#57]
**In email was questioned**

...
The Consent API has a ‘Status’ but I couldn’t find anywhere the ‘Life Cycle’ of the Consent API was documented.
The Consent API States should have the following states (or equivalent)
Created – New Consent with no details yet populated by the Banks Customer.
AwaitingAuthorisation –  A user has authenticated with this scope / consent id and the user matches the TPP Asserted Identity so the Bank and TPP knows that the user has authenticated. The User has authorized the OAuth 2.0 flow but additional authorisation is required. (will be required for business payments). This state transition is optional
Authorised – All necessary customers have authorised the access.
Rejected – The user did not authorise the consent.
Revoked – The customer revoked the consent at the Bank
...

**This is response**

According to the documentation (https://openbanking-brasil.github.io/areadesenvolvedor/#criar-novo-pedido-de-consentimento), when requesting the creation of consent and a response with return code 201 is returned (Created), a ResponseConsent is returned.
In the ResponseConsent definition (https://openbanking-brasil.github.io/areadesenvolvedor/#tocS_ResponseConsent) the status field is an enumeration with the values ​​below:

Enumerated Values
Name    Code
status  AUTHORISED
status  AWAITING_AUTHORISATION
status  REJECTED
status  REVOKED

As a result, the life cycle follows the same pattern as in the UK (https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/account-access-consents.html#status-flow)

![Diagram](https://openbankinguk.github.io/read-write-api-site3/assets/img/ConsentAuthorisation.51622ffd.jpg)

**Comment by RalphBragg** [comment]
Hi,

The reason i raised this question is that the 'revoked' state was removed from the UK in 3.1.4.  Consents are no longer Revoked they are simply deleted.

Look at the table in documentation 

<h4 id="account-access-consent-status-2" style="font-weight: 600; line-height: 1.25; margin-top: -6.7rem; padding-top: 8.2rem; margin-bottom: 0px; color: rgb(0, 0, 0); font-family: Metropolis, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Account Access Consent Status</h4><p style="line-height: 1.7; color: rgb(0, 0, 0); font-family: Metropolis, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Once the PSU authorises the account-access-consent resource - the Status of the account-access-consent resource will be updated with "Authorised".</p><p style="line-height: 1.7; color: rgb(0, 0, 0); font-family: Metropolis, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The available Status code-list enumerations for the account-access-consent resource are:</p>
&nbsp; | Status | Status Description
-- | -- | --
1 | Rejected | The account access consent has been rejected.
2 | AwaitingAuthorisation | The account access consent is awaiting authorisation.
3 | Authorised | The account access consent has been successfully authorised.
4 | Revoked | The account access consent has been revoked via the ASPSP interface. This status is not applicable for the resource created after Ver 3.1.4.

<h3 id="delete-account-access-consents-consentid" style="font-weight: 600; line-height: 1.25; font-size: 1.35rem; margin-top: -6.7rem; padding-top: 8.2rem; margin-bottom: 0px; color: rgb(0, 0, 0); font-family: Metropolis, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/account-access-consents.html#delete-account-access-consents-consentid" class="header-anchor" style="font-weight: 500; text-decoration: none; color: rgb(97, 128, 195); font-size: 0.85em; float: left; margin-left: -0.87em; padding-right: 0.23em; margin-top: 0.125em; opacity: 0;">#</a></h3><br class="Apple-interchange-newline">

"The account access consent has been revoked via the ASPSP interface. This status is not applicable for the resource created after Ver 3.1.4."

**Comment by DeiGratia33** [comment]
We have a question to be answered by the legal team. My concern we are not going to be allowed to delete. We need to store the consent after revoked, maybe for 5+1 years.

**Comment by RalphBragg** [comment]
Thanks - having a revoked state is perfectly fine just don't point people at the U.K. specs as this state has been deprecated.

Will adding this ticket to functional API.

**Comment by RalphBragg** [comment]
@DeiGratia33  - can this be closed?

**Comment by DeiGratia33** [comment]
@RalphBragg , yes we can close.

**Comment by RalphBragg** [comment]
Do you close rights?

**Comment by DeiGratia33** [comment]
no, I am just a padawan

**Comment by RalphBragg** [comment]
@EkkeErick  - can we get Alex and Marcos Administration access pretty please.
