### ISSUE TITLE
Signature Certificate Template

### ISSUE THREAD

**Issue by originaljuca** [OpenBanking-Brasil/specs-seguranca#59]
Which template will be used on the signature certificate ? e-CNPJ ? e-PJ ? Other one ? A new one ?

**Comment by RalphBragg** [comment]
The certificate structures for signing and transport are inclduded in the certificate structure document.

**Comment by originaljuca** [comment]
Yes, theres some information there. But we need to know the certificate type that is going to be used : epj , e-cpnj , or a new one. And what are the CAs that will provide this service here in Brazil?

**Comment by RalphBragg** [comment]
Hi,

There are two new certificate types in the profile. https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-certificate-standards-1_ID1.md which were created by @DeiGratia33 and ITI.

In terms of Certificate Authority - i believe it is the Government Owned CA that has initially committed to issuing the new profiles. I will add this information to the WIKI FAQ

**Comment by originaljuca** [comment]
@DeiGratia33 Boa tarde. Teremos um novo tipo de certificado a ser emitido pelas autoridades certificadoras no brasil ? Ou será do tipo e-cpnj ou e-pj ?
