### ISSUE TITLE
Add missing screen shots to the user guides

### ISSUE THREAD

**Issue by RalphBragg** [OpenBanking-Brasil/specs-seguranca#6]
Add missing screen shots to the user guides

**Comment by RalphBragg** [comment]
As part of this ticket all of the images and web sequence diagrams need to be moved to an images folder in git with appropriate naming and standardization.

**Comment by ediemerson-br** [comment]
@RalphBragg, is just the SVG image format allowed by oauthstuff/markdown2rfct tool?
