### ISSUE TITLE
Exclusion of Consent

### ISSUE THREAD

**Issue by carlosaaf** [OpenBanking-Brasil/specs-seguranca#60]
**In email was questioned**

...
The API also needs guidance such as

TPPs must delete consent resources that have expired, been revoked by the customer at the TPP, Rejected by the customer once the TPP has process their rejection, detected as being revoked by the customer at the bank.
Banks may delete consent resources that have expired X months after the access expiry.
Banks may delete consent resources that have been Rejected by the customer after X days.
Banks may delete consent resources that have not been Authorised (because of delays with multi party authorisation) after X weeks.
Banks may delete consent resources after X period (minutes, hours, days?) after notification of the revocation of an the OAuth Client from the Open Banking Directory.
This is actually quite important. When a TPP gets revoked from the directory we move all of the keys out of the active key sets into the inactive keysets but this can be recovered relatively easily if a TPP makes a mistake.
If a TPP makes a mistake and the Banks immediately revoke all of the consents this can’t be walked back and so has significant impact to the ecosystem so putting a delay here might not be the worst idea.
 

Alternatively

Banks may not delete consent resources at all except on notification of the revocation of a TPP’s OAuth client. (Simpler but requires TPPs to be well behaved).
...

**This is the answer**

As for the exclusion of revoked or rejected consents, the strategy described by Ralph, where these consents are moved to an archive, represents a very adequate solution. It does not affect the performance of operations with valid consents, nor does it lose the history of these consents.

According to Resolution no. 1 art. 49 (https://www.bcb.gov.br/pre/normativos/busca/downloadNormativo.asp?arquivo=/Lists/Normativos/Attachments/51028/Res_Conj_0001_v1_O.pdf) must be available to the Central Bank for 5 years:
- revoked consents (art.15) with their respective reason for revocation, for example, by time (expired consent) or by order of the user who owns the consent
- rejected consents (art. 26) with their respective reason, for example, by time (waiting for authorization for more than 60 minutes) or by order of the user who owns the consent

* The 60-minute time represents the time set for a user to approve consent. This time has not yet been approved by the council.

**Comment by RalphBragg** [comment]
Hi,

Just to confirm that Banks are allowed to clean up resources i.e delete them provided that they are available to the central bank on request from an archive?

Kind Regards,
Ralph

**Comment by DeiGratia33** [comment]
Run a garbage collector is the proposal from the Security WG, as the time of 60 minutes to wait for approval of consent.

The Security WG is going to make a proposal to specify this, but asking for revision of the Jurídica WG to make sure we are not violating anything here.

**Comment by DeiGratia33** [comment]
I have a included change request that is not specifying the time exactly, but clarifies the cycle of revoke, and store as required by regulation prior delete.

**Comment by RalphBragg** [comment]
@DeiGratia33 - can this then be closed?

**Comment by DeiGratia33** [comment]
Yes. We can close.
