### ISSUE TITLE
Question: Method for client authentication (DCR)

### ISSUE THREAD

**Issue by msauaia** [OpenBanking-Brasil/specs-seguranca#65]
The specs for certificates (open-banking-brasil-certificate-standards-1_ID1.md) stablishes that 

"_Client Certificates are also used to authenticate the client application through 
oAuth 2.0 mTLS or private_key_jwt, according to the application's registration 
carried out by the Dynamic Client Registration process with the transmitting entity_."

Does this leave the ASPSP discretion to choose the method it will use or should it implement both methods, oAuth 2.0 mTLS and private_key_jwt?

If is mandatory to the ASPSP implement the private_key_jwt method, which are the obligatory claims?

**Comment by RalphBragg** [comment]
According to the published security profile banks can implement either or both. Provided they advertise support for at least one of the two supported mechanisms then they will be compliant.

**Comment by FrancoPeluti** [comment]
@RalphBragg, By choosing just one of the methods, won't it be a trouble for certifying in FAPI OpenID Foundation Certification?

**Comment by RalphBragg** [comment]
No, the framework allows you to specify exactly what options you want to certify your implementation for. 

For example, we have certified the directory against 4 profiles by choice but you will only have to certify one.

The process allows you to verify as many different profiles as you like in one certification application,

**Comment by RalphBragg** [comment]
@msauaia - can we close this ticket now please?

**Comment by RalphBragg** [comment]
![image](https://user-images.githubusercontent.com/35098287/120868470-0979c280-c58c-11eb-8cfa-141ba3330640.png)

@FrancoPeluti  - I included this screen shot so you can see how you can select what elements of FAPI you want to test your authorization server for.

**Comment by DeiGratia33** [comment]
@FrancoPeluti , @msauaia , I believe we can close. Correct?
