### ISSUE TITLE
Certificate Standard - "Subject Alternative Name" of sign certificate

### ISSUE THREAD

**Issue by msauaia** [OpenBanking-Brasil/specs-seguranca#66]
The specs for certificates (open-banking-brasil-certificate-standards-1_ID1.md) stablishes that sign certificate must contain in "Subject Alternative Name" the informations of the responsible for the certificate. 

Does this person need to be the same person who registered the application in the onboarding process in the directory?

If they are different person, will the CA need to validate this information from the responsible through calls to the directory?

Is this certificate e-cnpj standard?

**Comment by DeiGratia33** [comment]
All the process included in the validation of the SAN attribute of the certificates is established by the current ICP-Brasil definition, which does not required to be the same person who registered the application at the directory.
