### ISSUE TITLE
TPP User Guide Not matching developer area specs

### ISSUE THREAD

**Issue by andreborges01** [OpenBanking-Brasil/specs-seguranca#68]
We verified that in TPP User Guide doc from line 584 (4.2 Creating Consent), the content present does not match with Brazilian specification shown in **https://openbanking-brasil.github.io/areadesenvolvedor/#criar-novo-pedido-de-consentimento**

Could you please verify?

**Comment by RalphBragg** [comment]
Thank you - this has been corrected.
