### ISSUE TITLE
Remove all CPF and CNPJ mentions from TTP user Guide

### ISSUE THREAD

**Issue by andreborges01** [OpenBanking-Brasil/specs-seguranca#70]
As per group definition of sending CPF and CNPJ in the Consent API, please remove all mention of CPF and CNPJ from  TPP User Guide:

1 - Remove CPF from Request Object
2 - Remove CPF and CPNJ mention from Appendix A2
3 - Remove  CPF and CPNJ from second A2 - specific claim value

Thanks

**Comment by RalphBragg** [comment]
Alex & Marcos - can you please provide the latest update to Andre please on these items. The language has already been clarified however the need for the claims is required for different reasons.
