### ISSUE TITLE
Remove All CPF and CNPJ mentions from Security Profile

### ISSUE THREAD

**Issue by andreborges01** [OpenBanking-Brasil/specs-seguranca#71]
As per group definition of sending CPF and CNPJ in the Consent API, please remove all mention of CPF and CNPJ from Security Profile:

1 - Remove from Security Profile, in topic Authorization Server item 4, 5 and 12.
2 - Remove from Security Profile, item Request the "cpf" Claim and Request the "cnpj" Claim
3 - Remove from Security Profile, item 6 from Confidential Client
4 - Remove from Security Profile, Requirement on Client present cpf claim to AS

**Comment by RalphBragg** [comment]
Alex & Marcos - can you please provide the latest update to Andre please on these items. The language has already been clarified however the need for the claims is required for different reasons.
