### ISSUE TITLE
Question: consentId pattern and security profile dynamic scope consent format and namespace

### ISSUE THREAD

**Issue by ginglass** [OpenBanking-Brasil/specs-seguranca#72]
Hello guys, although ``consentId`` pattern described on [swagger file](https://openbanking-brasil.github.io/areadesenvolvedor/swagger/swagger_consents_apis.yaml) (line 496) matches the definition at Dynamic Scope Consent section (security profile doc), I suggest a more specific regex on a new version of consents API. Dont you agree? If you don´t, fell free to close this issue :-).

Where does bank namespace definition (bank short name, "bancoex" on that example) came from? Each bank could define yours?

==> pattern: '^[a-zA-Z0-9][a-zA-Z0-9\-]{0,99}$' (line 496) vs this format:  "urn-bancoex-C1DD33123"

**Comment by msauaia** [comment]
The understanding of my institution's developers is that the standard defined in the swagger meets the type of data that is intended to be passed.

In the specific case at my institution, we would like to pass this information in UUID format, which would comply with the swagger standard. However, if we specify a more closed pattern to specifically meet the string "urn-bancoex-C1DD33123", the data in the UUID pattern would not be possible.

In view of the above, we ask the following: will it be mandatory to follow the pattern in the string "**urn-bancoex-C1DD33123**" or we can pass a data that fits the pattern defined by the swagger pattern: '**^ [a-zA-Z0-9] [a-zA-Z0-9 -] {0.99} $** '?

**Comment by RalphBragg** [comment]
The swagger specification for the consentId payload must be followed and respected however the security profile also requires the following
In addition:

the Consent Resource Id must include url safe characters only;
the Consent Resource Id must be namespaced;
the Consent Resource Id must have the properties of a nonce;

So provided that it meets those properties you can use whatever format you like e.g bancoex-UUID would be fine.

**Comment by RalphBragg** [comment]
Hi,

Can this ticket now be closed?

**Comment by ginglass** [comment]
Yes, please. Thank you.
