### ISSUE TITLE
software statement examples in client registration spec should align with RFC7591 (oauth2 DCR)

### ISSUE THREAD

**Issue by jogu** [OpenBanking-Brasil/specs-seguranca#73]
As per:

https://datatracker.ietf.org/doc/html/rfc7591#section-2

the example here:

https://github.com/OpenBanking-Brasil/specs-seguranca/blame/main/open-banking-brasil-dynamic-client-registration-1_ID1.md#L286

differs in names of the following keys - the RFC does not have the `software_` prefix:

`software_client_name` -> `client_name`

`software_client_description` -> `client_description`

`software_jwks_uri` -> `jwks_uri`

`software_policy_uri` -> `policy_uri`

and so on.

(The only two fields in the RFC that go in the software statement and are prefixed `software_` are: `software_id` and `software_version`.)

I believe the intent is for software that already supports RFC7591 to be able to process the software statements so the example should be updated.

**Comment by RalphBragg** [comment]
This is a bug, I'll correct it tonight. Those keys are in the SSA not in the dcr payload. I have to incorporate another change at the request of the security wg now.

**Comment by RalphBragg** [comment]
This is not a bug - these claims are metadata from an SSA not claims as part of an RFC7591 request. 
These claims mirror the UK standards https://github.com/OpenBankingUK/directory-api-specs/blob/master/directory-api-swagger.yaml and so should be familiar to implementers

**Comment by jogu** [comment]
Thanks for the explanation Ralph! It's a bit odd (in the same way the UK spec is) and probably would've been preferable for the SSA entries that appear to match the RFC7591 behaviour for SSA entries to have the same names, and only to use new names where behaviour differs from the RFC... I'll close this then.
