### ISSUE TITLE
DCR scopes typos?

### ISSUE THREAD

**Issue by alexasensio** [OpenBanking-Brasil/specs-seguranca#80]
DCR specification: for allowed scopes for [Regulatory Role](https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-dynamic-client-registration-1_ID1.md#regulatory-roles-to-openid-and-oauth-20-mappings) DADOS contain:

- "_consents_" twice in the list. Is this correct or a typo? If correct, what is the implication of having a scope duplicated?

- "_unarragned-accounts-overdraft_". Expected value "_unarra**ng**ed-accounts-overdraft_"

**Comment by RalphBragg** [comment]
There's no issue with having the scope listed twice. There is an obvious issue with having the typo listed however as it is an errata change i'll get it corrected in the PR that is still with the Brazil Security Team to approve.
