### ISSUE TITLE
Value of software_version in OBB FAPI DCR 1.0 Section 8.1

### ISSUE THREAD

**Issue by TakahikoKawasaki** [OpenBanking-Brasil/specs-seguranca#83]
The value of `"software_version"` in "[8.1. Software Statement Claims](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html#name-software-statement-claims)" of [OBB FAPI DCR 1.0 ID1](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html) is `1.1`, but it should be `"1.1"`.

"[2. Client metadata](https://www.rfc-editor.org/rfc/rfc7591.html#section-2)" of [RFC 7591](https://www.rfc-editor.org/rfc/rfc7591.html) says that `"software_version"` is a _"version identifier **string**"_.

**Comment by RalphBragg** [comment]
The generated SSA is correctly a string already "software_version": "2.00". This is a documentation issue that will be corrected.
