### ISSUE TITLE
Question: Which claims in SSA should be kept as client metadata?

### ISSUE THREAD

**Issue by TakahikoKawasaki** [OpenBanking-Brasil/specs-seguranca#84]
The example shown in "[8.1. Software Statement Claims](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html#name-software-statement)" of "[OBB FAPI DCR 1.0 ID1](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html)" includes claims that are not defined in [RFC 7591](https://www.rfc-editor.org/rfc/rfc7591.html) and other global standards. Which claims should be kept as client metadata and which claims don't have to be? In other words, which claims should the authorization server return when it receives a "Client Read Request" which is defined in "[2.1. Client Read Request](https://www.rfc-editor.org/rfc/rfc7592.html#section-2.1)" of [RFC 7592](https://www.rfc-editor.org/rfc/rfc7592.html)?

The list below shows the non-standard claims.

1. `software_mode`
2. `software_redirect_uris`
3. `software_statement_roles`
4. `software_client_name`
5. `org_status`
6. `software_client_id`
7. `software_tos_uri`
8. `software_client_description`
9. `software_jwks_uri`
10. `software_policy_uri`
11. `software_client_uri`
12. `software_jwks_inactive_uri`
13. `software_jwks_transport_inactive_uri`
14. `software_jwks_transport_uri`
15. `software_logo_uri`
16. `org_id`
17. `org_number`
18. `software_environment`
19. `software_roles`
20. `org_name`
21. `organisation_competent_authority_claims`

Some of the claims above are found in [directory-api-swagger.yaml](https://github.com/OpenBankingUK/directory-api-specs/blob/master/directory-api-swagger.yaml) under [OpenBankingUK](https://github.com/OpenBankingUK)/[directory-api-specs](https://github.com/OpenBankingUK/directory-api-specs), but the OBB DCR specification itself does not describe its relationship with UK Open Banking.

Clarification on each non-standard claim is needed for implementers.

**Comment by RalphBragg** [comment]
What information and metadata needs to be used and kept is primarily driven by the UI/UX guidelines which have yet to be published on this topic. e.g in the United Kingdom, the organisations name and org number typically has to be shown to customers. These requirements are pending from the UI / UX team.
@DeiGratia33

**Comment by ediemerson-br** [comment]
If you have further question, you can create a service desk ticket.
https://servicedesk.openbankingbrasil.org.br/Login.jsp
