### ISSUE TITLE
Question: Default Scope on Dynamic Client Registration

### ISSUE THREAD

**Issue by TakahikoKawasaki** [OpenBanking-Brasil/specs-seguranca#85]
"[7.2. Regulatory Roles to OpenID and OAuth 2.0 Mappings](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html#name-regulatory-roles-to-openid-)" of "[OBB FAPI DCR 1.0 ID1](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html)" states as follows.

> If the scopes are omitted during the DCR process, the authorization server shall grant the complete set of potential scopes based on the registering bank's regulatory roles, as described in the Server Defaults section.

This requirement implies that the `"software_roles"` claim in SSA should be referred to. But SSA also has the `"software_statement_roles"`. Which should be used?

If `"software_statement_roles"` should be used, should the authorization server take the `"status"` property of each element in `"software_statement_roles"` into consideration?

Also, where is "the Server Defaults section"?

**Comment by RalphBragg** [comment]
@TakahikoKawasaki  - Status should be taken into consideration however, as per the UK model, software roles are additive only. If an application loses a particular regulatory permission then the application will be revoked. This means as it current stands you could process just the simple array software_roles if you chose too.

**Comment by RalphBragg** [comment]
eyJraWQiOiJzaWduZXIiLCJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiJ9.eyJzb2Z0d2FyZV9qd2tzX2luYWN0aXZlX3VyaSI6Imh0dHBzOlwvXC9rZXlzdG9yZS5zYW5kYm94LmRpcmVjdG9yeS5vcGVuYmFua2luZ2JyYXNpbC5vcmcuYnJcLzc0ZTkyOWQ5LTMzYjYtNGQ4NS04YmE3LWMxNDZjODY3YTgxN1wvOGQ2MWY1OWEtYmEwYi00NzRkLTg4ZTctYWYzMGJkZjAxMjI2XC9pbmFjdGl2ZVwvYXBwbGljYXRpb24uandrcyIsInNvZnR3YXJlX21vZGUiOiJMaXZlIiwic29mdHdhcmVfcmVkaXJlY3RfdXJpcyI6WyJodHRwczpcL1wvbG9jYWxob3N0LnRwcFwvY2IiXSwic29mdHdhcmVfc3RhdGVtZW50X3JvbGVzIjpbeyJyb2xlIjoiREFET1MiLCJhdXRob3Jpc2F0aW9uX2RvbWFpbiI6Ik9wZW4gQmFua2luZyBCcmFzaWwgIiwic3RhdHVzIjoiQWN0aXZlIn0seyJyb2xlIjoiUEFHVE8iLCJhdXRob3Jpc2F0aW9uX2RvbWFpbiI6Ik9wZW4gQmFua2luZyBCcmFzaWwgIiwic3RhdHVzIjoiQWN0aXZlIn1dLCJzb2Z0d2FyZV9jbGllbnRfbmFtZSI6Ik1vY2sgQmFuayBjbGllbnQgMiIsIm9yZ19zdGF0dXMiOiJBY3RpdmUiLCJzb2Z0d2FyZV9jbGllbnRfaWQiOiJ6YU5xWTBGaTQ2NG41WWRiY01BYmgiLCJpc3MiOiJPcGVuIEJhbmtpbmcgT3BlbiBCYW5raW5nIEJyYXNpbCBzYW5kYm94IFNTQSBpc3N1ZXIiLCJzb2Z0d2FyZV90b3NfdXJpIjoiaHR0cHM6XC9cL3JhaWRpYW0uY29tXC90b3MuaHRtbCIsInNvZnR3YXJlX2p3a3NfdHJhbnNwb3J0X2luYWN0aXZlX3VyaSI6Imh0dHBzOlwvXC9rZXlzdG9yZS5zYW5kYm94LmRpcmVjdG9yeS5vcGVuYmFua2luZ2JyYXNpbC5vcmcuYnJcLzc0ZTkyOWQ5LTMzYjYtNGQ4NS04YmE3LWMxNDZjODY3YTgxN1wvOGQ2MWY1OWEtYmEwYi00NzRkLTg4ZTctYWYzMGJkZjAxMjI2XC9pbmFjdGl2ZVwvdHJhbnNwb3J0Lmp3a3MiLCJzb2Z0d2FyZV9wb2xpY3lfdXJpIjoiaHR0cHM6XC9cL3JhaWRpYW0uY29tXC9wb2xpY3kuaHRtbCIsInNvZnR3YXJlX2lkIjoiOGQ2MWY1OWEtYmEwYi00NzRkLTg4ZTctYWYzMGJkZjAxMjI2Iiwic29mdHdhcmVfandrc190cmFuc3BvcnRfdXJpIjoiaHR0cHM6XC9cL2tleXN0b3JlLnNhbmRib3guZGlyZWN0b3J5Lm9wZW5iYW5raW5nYnJhc2lsLm9yZy5iclwvNzRlOTI5ZDktMzNiNi00ZDg1LThiYTctYzE0NmM4NjdhODE3XC84ZDYxZjU5YS1iYTBiLTQ3NGQtODhlNy1hZjMwYmRmMDEyMjZcL3RyYW5zcG9ydC5qd2tzIiwic29mdHdhcmVfY2xpZW50X3VyaSI6Imh0dHBzOlwvXC9yYWlkaWFtLmNvbSIsInNvZnR3YXJlX2xvZ29fdXJpIjoiaHR0cHM6XC9cL3JhaWRpYW0uY29tXC9sb2dvLmh0bWwiLCJvcmdfaWQiOiI3NGU5MjlkOS0zM2I2LTRkODUtOGJhNy1jMTQ2Yzg2N2E4MTciLCJvcmdfbnVtYmVyIjoiMTMzNTMyMzYwMDE4OSIsInNvZnR3YXJlX2p3a3NfdXJpIjoiaHR0cHM6XC9cL2tleXN0b3JlLnNhbmRib3guZGlyZWN0b3J5Lm9wZW5iYW5raW5nYnJhc2lsLm9yZy5iclwvNzRlOTI5ZDktMzNiNi00ZDg1LThiYTctYzE0NmM4NjdhODE3XC84ZDYxZjU5YS1iYTBiLTQ3NGQtODhlNy1hZjMwYmRmMDEyMjZcL2FwcGxpY2F0aW9uLmp3a3MiLCJzb2Z0d2FyZV9lbnZpcm9ubWVudCI6IkRldmVsb3BtZW50Iiwic29mdHdhcmVfdmVyc2lvbiI6IjIuMDAiLCJzb2Z0d2FyZV9yb2xlcyI6WyJEQURPUyIsIlBBR1RPIl0sIm9yZ19uYW1lIjoiT3BlbiBCYW5raW5nIEJyYXNpbCIsImlhdCI6MTYyMzA1ODA2MSwib3JnYW5pc2F0aW9uX2NvbXBldGVudF9hdXRob3JpdHlfY2xhaW1zIjpbeyJhdXRob3Jpc2F0aW9uX2RvbWFpbiI6Ik9wZW4gQmFua2luZyBCcmFzaWwgIiwiYXV0aG9yaXNhdGlvbnMiOlt7Im1lbWJlcl9zdGF0ZSI6IkJSIn1dLCJyZWdpc3RyYXRpb25faWQiOiJDTlBKLU9CQi1EQURPUyIsImF1dGhvcml0eV9uYW1lIjoiQmFuY28gQ2VudHJhbCBEbyBCcmFzaWwiLCJhdXRob3JpdHlfaWQiOiI1MzYwZDViZi01MDI0LTQ3Y2QtYmQxOC1kYWFiMDhkZjM4YmEiLCJhdXRob3Jpc2F0aW9uX3JvbGUiOiJEQURPUyIsImF1dGhvcml0eV9jb2RlIjoiQkNCIiwic3RhdHVzIjoiQWN0aXZlIn0seyJhdXRob3Jpc2F0aW9uX2RvbWFpbiI6Ik9wZW4gQmFua2luZyBCcmFzaWwgIiwiYXV0aG9yaXNhdGlvbnMiOltdLCJyZWdpc3RyYXRpb25faWQiOiJDTlBKLU9CQi1QQUdUTyIsImF1dGhvcml0eV9uYW1lIjoiQmFuY28gQ2VudHJhbCBEbyBCcmFzaWwiLCJhdXRob3JpdHlfaWQiOiI1MzYwZDViZi01MDI0LTQ3Y2QtYmQxOC1kYWFiMDhkZjM4YmEiLCJhdXRob3Jpc2F0aW9uX3JvbGUiOiJQQUdUTyIsImF1dGhvcml0eV9jb2RlIjoiQkNCIiwic3RhdHVzIjoiQWN0aXZlIn0seyJhdXRob3Jpc2F0aW9uX2RvbWFpbiI6Ik9wZW4gQmFua2luZyBCcmFzaWwgIiwiYXV0aG9yaXNhdGlvbnMiOltdLCJyZWdpc3RyYXRpb25faWQiOiJVbmlxUmVnaXN0cmF0aW9uSWQiLCJhdXRob3JpdHlfbmFtZSI6IkJhbmNvIENlbnRyYWwgRG8gQnJhc2lsIiwiYXV0aG9yaXR5X2lkIjoiNTM2MGQ1YmYtNTAyNC00N2NkLWJkMTgtZGFhYjA4ZGYzOGJhIiwiYXV0aG9yaXNhdGlvbl9yb2xlIjoiVFJEIiwiYXV0aG9yaXR5X2NvZGUiOiJCQ0IiLCJzdGF0dXMiOiJJbmFjdGl2ZSJ9XX0.p4mHTF0sVIMmXqiPPPdCJr7hYYH1bnYEY16T-y6s-voAEUiBSYoSsLxGibc4MWKDOfNqNVoKTLyKTy7NfV0_Oq7DjyBBaygcFNhSOfdxLznltlkRcEXUzLAzaoyvpUZW-Dno0HR4rN_V0QKXqtacWyMH0t_sCdCnWWRY5_LKxXSI7KPjowJycpidp7BsihSq11UInUGf4YdRti1p1_1APVET87FtVocq0adUvLQEddXxHNtha8P3RlehjrRkqqp1GescIGb6TTdFO4wFBh3SQJBHnwsB0JEL_959C51Fx7-oN2Bqt1UH-ddRU6LdEkm_NVMGbZ2vNHv6IovaLcZiKQ

**Comment by TakahikoKawasaki** [comment]
@RalphBragg Thank you. I could understand. If the operation does not change, checking the `"software_roles"` array is enough.
