### ISSUE TITLE
Questions: Signature and encryption of the request object (JWS x JWE)

### ISSUE THREAD

**Issue by msauaia** [OpenBanking-Brasil/specs-seguranca#87]
In the specification of the Authorization server, item 1 requires the implementation of signature and encryption of the request object (JWE). We understand that this was a requirement when there was a need to pass cpf / cnpj at the time of referral for authorization.

As there is no longer this need as (above), we understand that this item should be reformulated for JWS instead of JWE (only signed, nothing encrypted ).

**Comment by RalphBragg** [comment]
Hi - the latest commentary of the security working group allows and retains the technical capability for CPF to be requested on authentication as a standard claim. As banks have to support the OIDC claims parameter as defined in OIDC Core but must do so in a privacy preserving manner the requirement to support encrypted request objects OR pushed Authorization requests persists.

**Comment by RalphBragg** [comment]
Confirming that this requirement will be in the security profile developed from the OIDF for Brazil

**Comment by msauaia** [comment]
Okay. But just to clarify one point.

We understand that JWE would be needed only in cases where there is a need to pass PII on requests.

It turns out that this is not a case of intended use. So, we understand that JWE would not be mandatory for phase 2. Is that correct?

We understand that there is a need to pass the CPF field in requests as a claim, in accordance with item "5.5.1. Individual Claims Requests" of the OIDF, but this claim is empty, just to guide the return to have the information. It happens that the requester can request that this claim come in userinfo or in the token ID. If it comes in userinfo, the use of JWE is not necessary. Is this understanding correct?

**Comment by DeiGratia33** [comment]
Correct, for request, if you support PAR. 


For return
FAPI Advanced
"should not return sensitive PII in the ID Token in the authorization response, but if it needs to, then it should encrypt the ID Token."

**Comment by RalphBragg** [comment]
If you don't support par then you need to support encrypted request objects and will fail conformance if you don't.

**Comment by RalphBragg** [comment]
Hi,

This is a subtle distinction that i think is being lost. If a tpp requests that the bank provides a cpf value then a bank can simply sign the response.

If a tpp requests that a cpf matches a specific required value, as per oidc code (8 year old spec) then it must encrypt them request object which means banks must support encrypted request objects (or par). This is as per oidc core so should be a standard requirement for all fapi compliant vendors.

RB
