### ISSUE TITLE
Add example RFC7592 + Brazil SSA to DCR Specification Appendix

### ISSUE THREAD

**Issue by esachser** [OpenBanking-Brasil/specs-seguranca#89]
Hi,

When a client is performing an update, it shall send a new SSA who certifies the new configuration?
The validations in the update are the same as in the registration?

**Comment by RalphBragg** [comment]
That is correct, the validation of the SSA must be same otherwise clients could register a client using an SSA and then just alter it as they saw fit. The update with another SSA allows additions (like a new redirect uri) or the addition of a regulatory role to a software statement to be communicated from the Client to the AS/OP.

**Comment by esachser** [comment]
There will be an update to the documentation stating that information or the answers of the issues are normative?

**Comment by RalphBragg** [comment]
@esachser  - I'm sorry, could you let me know what isn't clear about. **'These provisions apply equally to the processing of [RFC7591], [RFC7592] and [OpenID Registration][OIDR] requests'** which is included as part of the Authorisation Server requirements?

**Comment by esachser** [comment]
The RFC7592 doesn't states that for **updates** the SSA is obligatory, nor RFC7591 or OIDR, that's a characteristic of our DCR, and, as such, should be documented (I think).

**Comment by RalphBragg** [comment]
Correct - and our DCR specification says these rules shall be followed and that the rules apply to...

Authorization server
The Authorization Server shall support the [RFC7591], [RFC7592] and [OpenID Registration][OIDR]

In addition, the Authorization Server

**shall validate that the request contains software_statement jwt signed using using the PS256 alg issued by the open banking brasil directory of participants;**
... [ brevity]
These provisions apply equally to the processing of [RFC7591], **[RFC7592]** and [OpenID Registration][OIDR] requests

**Comment by esachser** [comment]
Understood. Thanks.
It would be great if some examples of update were added to the docs, just for clarification (to others like me).

**Comment by RalphBragg** [comment]
Can do, if it's unclear then adding a worked example for  an update to the appendixs might help. Will create a PR

**Comment by joaorodolfo** [comment]
We have already updated the DCR/DCM doc. If you cat more gaps please let we know. Thanks.
