### ISSUE TITLE
Remove all portuguese specification

### ISSUE THREAD

**Issue by DeiGratia33** [OpenBanking-Brasil/specs-seguranca#90]
As a manner to concentrate the changes over a single document, at the Github, would be preferable to maintain only the English version.

**Comment by RalphBragg** [comment]
@alex-siqueira  @ginglass  - can you confirm that this is agreed and you're going to do this. I really need to create a new working draft with issues and fixes that are being raised by the community. They can't go into ID1

**Comment by ediemerson-br** [comment]
We'll remove the Portuguese documents when we publish their content on "Portal do Desenvolvedor" (https://openbanking-brasil.github.io/areadesenvolvedor/). Probably next week.

**Comment by RalphBragg** [comment]
OK - can I crate the new WG? Working draft? There’s bugs in ID1 (or missing features) that the security team need to opine on that would require a new version.

________________________________

**Comment by ediemerson-br** [comment]
Sounds like a good idea!

**Comment by joaorodolfo** [comment]
It's solved for now, it will move to new Confluence platform, then we can talk about the best approach to keep all docs updated.
