### ISSUE TITLE
Question: Certificate-Bound Registration Access Token

### ISSUE THREAD

**Issue by TakahikoKawasaki** [OpenBanking-Brasil/specs-seguranca#91]
The [OBB FAPI DCR](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-certificate-standards-1_ID1.html) specification requires that a Client Registration Request come with a client certificate. In addition, the sequence diagram in the specification indicates that the Client Registration Endpoint returns an "[RFC 7592](https://www.rfc-editor.org/rfc/rfc7592.html) Management Token". It is technically possible to bind the registration access token to the client certificate (cf. [RFC 8705](https://www.rfc-editor.org/rfc/rfc8705.html)).

Should registration access tokens be bound to a certificate?

**Comment by RalphBragg** [comment]
I would but it isn’t explicitly defined. By binding the token to the transport Cert it would prevent hijack. It isn’t explicitly called out as you’d need a valid SSA anyway to make changes to the registration. So you need a long lived token and short lived “token” / ssa but there is no harm binding it to a cerificate over and above as well.
