### ISSUE TITLE
Wrong RFC number on documentation

### ISSUE THREAD

**Issue by esachser** [OpenBanking-Brasil/specs-seguranca#92]
Probably a typo. On the section <https://openbanking-brasil.github.io/specs-seguranca/aspsp-user-guide.html#openid-connect---the-identity-layer-for-the-internet> the last RFC cited was RFC7591, but by the definition and previous information that one must be RFC7592

**Comment by RalphBragg** [comment]
Thanks - for the userguides, feel free to just raise a PR for fixing it. All comments and contributions welcome.
