### ISSUE TITLE
ID1 - Missing Feature - How to determine Access Token to ConsentId Binding as a TPP

### ISSUE THREAD

**Issue by RalphBragg** [OpenBanking-Brasil/specs-seguranca#98]
When a TPP sends a consent to be authorised by a Bank the consentId is conveyed as part of a dynamic scope string.
e.g consent:bank1-12345678

There is a major change to FAPI ID2 and FAPI 1 Advanced Final that removed the requirement for an Authorisation Server to provide the access token scopes back to a TPP on Authorization code exchange or refresh token usage if the scope wasn't altered by a Resource Owner during Authorisation.

_5.2.2-14 Scopes granted in the token endpoint response can now be omitted except in the case where the authorization request was passed in the front channel (via a web browser) and was not integrity protected. This means requests using a signed request object or PAR can adopt the standard OAuth2 behaviour of only returning the granted scopes if they're different from the requested scopes._
https://bitbucket.org/openid/fapi/src/master/FAPI_1.0/changes-between-id2-and-final.md

The UK Open Banking Profile and the Australian CDR profile  Inherits requirements from ID2 which means that AS's MUST return the AT scope each time the TPP asks for it. This means the TPP has a way to identify what RT. is bound to what consent resource. 

Brazil doesn't have the requirement for ASs to include the scope string on every response as this requirement was removed in FAPI 1 Final which is the base for the Brazil Security Profile. 

This capability is important for TPPs to have and needs to be added back in however there are alternatives.

1. Alter the functional APIs to allow an Authorization Code token to be used against the /consents endpoint which would return an array containing a single consent resource that the AT is linked too.
2. Add a new claim in the id_token or User Info payload to allow this be returned. This isn't particulary nice becaues you're mixing identity payloads to convey authorisation concerns which is something that brazil has been really good to avoid.
3. Include the following clause on AS requirements in

"shall return the list of granted scopes with the issued access token";

**Comment by ginglass** [comment]
Hello guys. At this moment, I prefer the third option. Don't you agree @alex-siqueira ?

**Comment by RalphBragg** [comment]
I personally prefer option 3 as well. All implementers that have ever implemented FAPI before can do it. It isn't a new standard. It is the same behaviour for every other jurisdiction. I will be bringing this back up with the FAPI WG, i think this is still required personally and potentially shouldn't have been removed.

**Comment by DeiGratia33** [comment]
@RalphBragg , in case of opaque tokens, any concerns over this option?

**Comment by RalphBragg** [comment]
No - tokens should be opaque in my opinion. If they are structured opaque (JWE) that's up to the bank.

The Bank AS issues the access token for a Bank resource server to consume... so it really doesn't matter what format it is.

**Comment by RalphBragg** [comment]
If there is no other comments i'll submit a pull request for this change

**Comment by michellebandarraChicago** [comment]
Na Reunião do GT Segurança de 17/03/2022, o GT entendeu que problema relatado na issue não é atual e já foi endereçado, logo, issue pode ser encerrada
